package com.gcloud.shop.domain;

public class AreaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_area.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_area.type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_area.name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_area.parent_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_area.zip
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String zip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_area.id
     *
     * @return the value of tb_shop_area.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_area.id
     *
     * @param id the value for tb_shop_area.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_area.type
     *
     * @return the value of tb_shop_area.type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_area.type
     *
     * @param type the value for tb_shop_area.type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_area.name
     *
     * @return the value of tb_shop_area.name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_area.name
     *
     * @param name the value for tb_shop_area.name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_area.parent_id
     *
     * @return the value of tb_shop_area.parent_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_area.parent_id
     *
     * @param parentId the value for tb_shop_area.parent_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_area.zip
     *
     * @return the value of tb_shop_area.zip
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_area.zip
     *
     * @param zip the value for tb_shop_area.zip
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }
}