package com.gcloud.shop.domain;

import java.util.Date;

public class GoodsVoucherPeriod {
    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_goods_voucher_period.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long id;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_goods_voucher_period.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String storeId;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_goods_voucher_period.voucher_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String voucherId;

    /**
     * 券类型，DISCOUNT（折扣券）、CASH（代金券） <p/>
     * This field corresponds to the database column tb_goods_voucher_period.voucher_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String voucherType;

    /**
     * 单位描述，分为： MINUTE（分钟） HOUR（小时） WEEK_DAY（星期几） DAY（日） WEEK（周） MONTH（月） ALL（整个销售周期） <p/>
     * This field corresponds to the database column tb_goods_voucher_period.unit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String unit;

    /**
     * 区间范围枚举，分为： INCLUDE（包含） EXCLUDE（排除） <p/>
     * This field corresponds to the database column tb_goods_voucher_period.rule
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String rule;

    /**
     * 区间范围值，参数类型为Number <p/>
     * This field corresponds to the database column tb_goods_voucher_period.value
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String value;

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This field corresponds to the database column tb_goods_voucher_period.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Byte status;

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This field corresponds to the database column tb_goods_voucher_period.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String platform;

    /**
     * 备注 <p/>
     * This field corresponds to the database column tb_goods_voucher_period.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_voucher_period.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_voucher_period.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_goods_voucher_period.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_goods_voucher_period.id
     *
     * @return the value of tb_goods_voucher_period.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_goods_voucher_period.id
     *
     * @param id the value for tb_goods_voucher_period.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_goods_voucher_period.store_id
     *
     * @return the value of tb_goods_voucher_period.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_goods_voucher_period.store_id
     *
     * @param storeId the value for tb_goods_voucher_period.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_goods_voucher_period.voucher_id
     *
     * @return the value of tb_goods_voucher_period.voucher_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getVoucherId() {
        return voucherId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_goods_voucher_period.voucher_id
     *
     * @param voucherId the value for tb_goods_voucher_period.voucher_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setVoucherId(String voucherId) {
        this.voucherId = voucherId == null ? null : voucherId.trim();
    }

    /**
     * 券类型，DISCOUNT（折扣券）、CASH（代金券） <p/>
     * This method returns the value of the database column tb_goods_voucher_period.voucher_type
     *
     * @return the value of tb_goods_voucher_period.voucher_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getVoucherType() {
        return voucherType;
    }

    /**
     * 券类型，DISCOUNT（折扣券）、CASH（代金券） <p/>
     * This method sets the value of the database column tb_goods_voucher_period.voucher_type
     *
     * @param voucherType the value for tb_goods_voucher_period.voucher_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setVoucherType(String voucherType) {
        this.voucherType = voucherType == null ? null : voucherType.trim();
    }

    /**
     * 单位描述，分为： MINUTE（分钟） HOUR（小时） WEEK_DAY（星期几） DAY（日） WEEK（周） MONTH（月） ALL（整个销售周期） <p/>
     * This method returns the value of the database column tb_goods_voucher_period.unit
     *
     * @return the value of tb_goods_voucher_period.unit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getUnit() {
        return unit;
    }

    /**
     * 单位描述，分为： MINUTE（分钟） HOUR（小时） WEEK_DAY（星期几） DAY（日） WEEK（周） MONTH（月） ALL（整个销售周期） <p/>
     * This method sets the value of the database column tb_goods_voucher_period.unit
     *
     * @param unit the value for tb_goods_voucher_period.unit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * 区间范围枚举，分为： INCLUDE（包含） EXCLUDE（排除） <p/>
     * This method returns the value of the database column tb_goods_voucher_period.rule
     *
     * @return the value of tb_goods_voucher_period.rule
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getRule() {
        return rule;
    }

    /**
     * 区间范围枚举，分为： INCLUDE（包含） EXCLUDE（排除） <p/>
     * This method sets the value of the database column tb_goods_voucher_period.rule
     *
     * @param rule the value for tb_goods_voucher_period.rule
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * 区间范围值，参数类型为Number <p/>
     * This method returns the value of the database column tb_goods_voucher_period.value
     *
     * @return the value of tb_goods_voucher_period.value
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * 区间范围值，参数类型为Number <p/>
     * This method sets the value of the database column tb_goods_voucher_period.value
     *
     * @param value the value for tb_goods_voucher_period.value
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method returns the value of the database column tb_goods_voucher_period.status
     *
     * @return the value of tb_goods_voucher_period.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method sets the value of the database column tb_goods_voucher_period.status
     *
     * @param status the value for tb_goods_voucher_period.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method returns the value of the database column tb_goods_voucher_period.platform
     *
     * @return the value of tb_goods_voucher_period.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method sets the value of the database column tb_goods_voucher_period.platform
     *
     * @param platform the value for tb_goods_voucher_period.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * 备注 <p/>
     * This method returns the value of the database column tb_goods_voucher_period.remark
     *
     * @return the value of tb_goods_voucher_period.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注 <p/>
     * This method sets the value of the database column tb_goods_voucher_period.remark
     *
     * @param remark the value for tb_goods_voucher_period.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_voucher_period.created
     *
     * @return the value of tb_goods_voucher_period.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_voucher_period.created
     *
     * @param created the value for tb_goods_voucher_period.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_voucher_period.modified
     *
     * @return the value of tb_goods_voucher_period.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_voucher_period.modified
     *
     * @param modified the value for tb_goods_voucher_period.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_goods_voucher_period.enable_status
     *
     * @return the value of tb_goods_voucher_period.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_goods_voucher_period.enable_status
     *
     * @param enableStatus the value for tb_goods_voucher_period.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}