package com.gcloud.shop.domain;

import java.util.Date;

public class GoodsVoucher {
    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_goods_voucher.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long id;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_goods_voucher.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String storeId;

    /**
     * 券类型，DISCOUNT（折扣券）、CASH（代金券） <p/>
     * This field corresponds to the database column tb_goods_voucher.voucher_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String voucherType;

    /**
     * 价值金额，单位（元） CASH类型为代金券金额 DISCOUNT类型为优惠封顶金额 在代金券类型时，value_amout与reduce_to_amount不能同时为空，不能同时不为空。 <p/>
     * This field corresponds to the database column tb_goods_voucher.value_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Double valueAmount;

    /**
     * 起步数量，用于指定可享受优惠的起步单品购买数量 <p/>
     * This field corresponds to the database column tb_goods_voucher.threshold_quantity
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long thresholdQuantity;

    /**
     * 起步金额，单位（元） <p/>
     * This field corresponds to the database column tb_goods_voucher.threshold_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Double thresholdAmount;

    /**
     * 减至金额，单位（元），代表券可抵扣至多少（代金券类型可选字段，折扣券不需要） <p/>
     * This field corresponds to the database column tb_goods_voucher.reduce_to_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Double reduceToAmount;

    /**
     * 商品原金额，单位（元），（代金券类型可选字段，折扣券不需要） <p/>
     * This field corresponds to the database column tb_goods_voucher.original_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Double originalAmount;

    /**
     * 券原折扣,0-1之间，做展示使用（折扣券类型可选字段，代金券不需要） <p/>
     * This field corresponds to the database column tb_goods_voucher.original_rate
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Double originalRate;

    /**
     * 折扣率，填写0-1间的小数且不包括0和1，如八折则传入0.8。（折扣券类型必选字段，代金券不需要） <p/>
     * This field corresponds to the database column tb_goods_voucher.discount_rate
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Double discountRate;

    /**
     * 领券之后多长时间内可以核销，单位：分钟，传入数值需大于1440（一天） <p/>
     * This field corresponds to the database column tb_goods_voucher.valid_period
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long validPeriod;

    /**
     * 券的描述信息，目前客户端将统一展示“折扣须知” <p/>
     * This field corresponds to the database column tb_goods_voucher.voucher_desc
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String voucherDesc;

    /**
     * 延迟生效时间（手动领取条件下，可跟valid_period组合使用） <p/>
     * This field corresponds to the database column tb_goods_voucher.delay_minute
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String delayMinute;

    /**
     * 折扣金额取整规则 AUTO_ROUNDING_YUAN：自动抹零到元 AUTO_ROUNDING_JIAO：自动抹零到角 ROUNDING_UP_YUAN：四舍五入到元 ROUNDING_UP_JIAO：四舍五入到角 <p/>
     * This field corresponds to the database column tb_goods_voucher.rounding_rule
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String roundingRule;

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This field corresponds to the database column tb_goods_voucher.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Byte status;

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This field corresponds to the database column tb_goods_voucher.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String platform;

    /**
     * 备注 <p/>
     * This field corresponds to the database column tb_goods_voucher.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_voucher.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_voucher.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_goods_voucher.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_goods_voucher.id
     *
     * @return the value of tb_goods_voucher.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_goods_voucher.id
     *
     * @param id the value for tb_goods_voucher.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_goods_voucher.store_id
     *
     * @return the value of tb_goods_voucher.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_goods_voucher.store_id
     *
     * @param storeId the value for tb_goods_voucher.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * 券类型，DISCOUNT（折扣券）、CASH（代金券） <p/>
     * This method returns the value of the database column tb_goods_voucher.voucher_type
     *
     * @return the value of tb_goods_voucher.voucher_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getVoucherType() {
        return voucherType;
    }

    /**
     * 券类型，DISCOUNT（折扣券）、CASH（代金券） <p/>
     * This method sets the value of the database column tb_goods_voucher.voucher_type
     *
     * @param voucherType the value for tb_goods_voucher.voucher_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setVoucherType(String voucherType) {
        this.voucherType = voucherType == null ? null : voucherType.trim();
    }

    /**
     * 价值金额，单位（元） CASH类型为代金券金额 DISCOUNT类型为优惠封顶金额 在代金券类型时，value_amout与reduce_to_amount不能同时为空，不能同时不为空。 <p/>
     * This method returns the value of the database column tb_goods_voucher.value_amount
     *
     * @return the value of tb_goods_voucher.value_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Double getValueAmount() {
        return valueAmount;
    }

    /**
     * 价值金额，单位（元） CASH类型为代金券金额 DISCOUNT类型为优惠封顶金额 在代金券类型时，value_amout与reduce_to_amount不能同时为空，不能同时不为空。 <p/>
     * This method sets the value of the database column tb_goods_voucher.value_amount
     *
     * @param valueAmount the value for tb_goods_voucher.value_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setValueAmount(Double valueAmount) {
        this.valueAmount = valueAmount;
    }

    /**
     * 起步数量，用于指定可享受优惠的起步单品购买数量 <p/>
     * This method returns the value of the database column tb_goods_voucher.threshold_quantity
     *
     * @return the value of tb_goods_voucher.threshold_quantity
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getThresholdQuantity() {
        return thresholdQuantity;
    }

    /**
     * 起步数量，用于指定可享受优惠的起步单品购买数量 <p/>
     * This method sets the value of the database column tb_goods_voucher.threshold_quantity
     *
     * @param thresholdQuantity the value for tb_goods_voucher.threshold_quantity
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setThresholdQuantity(Long thresholdQuantity) {
        this.thresholdQuantity = thresholdQuantity;
    }

    /**
     * 起步金额，单位（元） <p/>
     * This method returns the value of the database column tb_goods_voucher.threshold_amount
     *
     * @return the value of tb_goods_voucher.threshold_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Double getThresholdAmount() {
        return thresholdAmount;
    }

    /**
     * 起步金额，单位（元） <p/>
     * This method sets the value of the database column tb_goods_voucher.threshold_amount
     *
     * @param thresholdAmount the value for tb_goods_voucher.threshold_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setThresholdAmount(Double thresholdAmount) {
        this.thresholdAmount = thresholdAmount;
    }

    /**
     * 减至金额，单位（元），代表券可抵扣至多少（代金券类型可选字段，折扣券不需要） <p/>
     * This method returns the value of the database column tb_goods_voucher.reduce_to_amount
     *
     * @return the value of tb_goods_voucher.reduce_to_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Double getReduceToAmount() {
        return reduceToAmount;
    }

    /**
     * 减至金额，单位（元），代表券可抵扣至多少（代金券类型可选字段，折扣券不需要） <p/>
     * This method sets the value of the database column tb_goods_voucher.reduce_to_amount
     *
     * @param reduceToAmount the value for tb_goods_voucher.reduce_to_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setReduceToAmount(Double reduceToAmount) {
        this.reduceToAmount = reduceToAmount;
    }

    /**
     * 商品原金额，单位（元），（代金券类型可选字段，折扣券不需要） <p/>
     * This method returns the value of the database column tb_goods_voucher.original_amount
     *
     * @return the value of tb_goods_voucher.original_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Double getOriginalAmount() {
        return originalAmount;
    }

    /**
     * 商品原金额，单位（元），（代金券类型可选字段，折扣券不需要） <p/>
     * This method sets the value of the database column tb_goods_voucher.original_amount
     *
     * @param originalAmount the value for tb_goods_voucher.original_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setOriginalAmount(Double originalAmount) {
        this.originalAmount = originalAmount;
    }

    /**
     * 券原折扣,0-1之间，做展示使用（折扣券类型可选字段，代金券不需要） <p/>
     * This method returns the value of the database column tb_goods_voucher.original_rate
     *
     * @return the value of tb_goods_voucher.original_rate
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Double getOriginalRate() {
        return originalRate;
    }

    /**
     * 券原折扣,0-1之间，做展示使用（折扣券类型可选字段，代金券不需要） <p/>
     * This method sets the value of the database column tb_goods_voucher.original_rate
     *
     * @param originalRate the value for tb_goods_voucher.original_rate
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setOriginalRate(Double originalRate) {
        this.originalRate = originalRate;
    }

    /**
     * 折扣率，填写0-1间的小数且不包括0和1，如八折则传入0.8。（折扣券类型必选字段，代金券不需要） <p/>
     * This method returns the value of the database column tb_goods_voucher.discount_rate
     *
     * @return the value of tb_goods_voucher.discount_rate
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Double getDiscountRate() {
        return discountRate;
    }

    /**
     * 折扣率，填写0-1间的小数且不包括0和1，如八折则传入0.8。（折扣券类型必选字段，代金券不需要） <p/>
     * This method sets the value of the database column tb_goods_voucher.discount_rate
     *
     * @param discountRate the value for tb_goods_voucher.discount_rate
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setDiscountRate(Double discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * 领券之后多长时间内可以核销，单位：分钟，传入数值需大于1440（一天） <p/>
     * This method returns the value of the database column tb_goods_voucher.valid_period
     *
     * @return the value of tb_goods_voucher.valid_period
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getValidPeriod() {
        return validPeriod;
    }

    /**
     * 领券之后多长时间内可以核销，单位：分钟，传入数值需大于1440（一天） <p/>
     * This method sets the value of the database column tb_goods_voucher.valid_period
     *
     * @param validPeriod the value for tb_goods_voucher.valid_period
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setValidPeriod(Long validPeriod) {
        this.validPeriod = validPeriod;
    }

    /**
     * 券的描述信息，目前客户端将统一展示“折扣须知” <p/>
     * This method returns the value of the database column tb_goods_voucher.voucher_desc
     *
     * @return the value of tb_goods_voucher.voucher_desc
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getVoucherDesc() {
        return voucherDesc;
    }

    /**
     * 券的描述信息，目前客户端将统一展示“折扣须知” <p/>
     * This method sets the value of the database column tb_goods_voucher.voucher_desc
     *
     * @param voucherDesc the value for tb_goods_voucher.voucher_desc
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setVoucherDesc(String voucherDesc) {
        this.voucherDesc = voucherDesc == null ? null : voucherDesc.trim();
    }

    /**
     * 延迟生效时间（手动领取条件下，可跟valid_period组合使用） <p/>
     * This method returns the value of the database column tb_goods_voucher.delay_minute
     *
     * @return the value of tb_goods_voucher.delay_minute
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getDelayMinute() {
        return delayMinute;
    }

    /**
     * 延迟生效时间（手动领取条件下，可跟valid_period组合使用） <p/>
     * This method sets the value of the database column tb_goods_voucher.delay_minute
     *
     * @param delayMinute the value for tb_goods_voucher.delay_minute
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setDelayMinute(String delayMinute) {
        this.delayMinute = delayMinute == null ? null : delayMinute.trim();
    }

    /**
     * 折扣金额取整规则 AUTO_ROUNDING_YUAN：自动抹零到元 AUTO_ROUNDING_JIAO：自动抹零到角 ROUNDING_UP_YUAN：四舍五入到元 ROUNDING_UP_JIAO：四舍五入到角 <p/>
     * This method returns the value of the database column tb_goods_voucher.rounding_rule
     *
     * @return the value of tb_goods_voucher.rounding_rule
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getRoundingRule() {
        return roundingRule;
    }

    /**
     * 折扣金额取整规则 AUTO_ROUNDING_YUAN：自动抹零到元 AUTO_ROUNDING_JIAO：自动抹零到角 ROUNDING_UP_YUAN：四舍五入到元 ROUNDING_UP_JIAO：四舍五入到角 <p/>
     * This method sets the value of the database column tb_goods_voucher.rounding_rule
     *
     * @param roundingRule the value for tb_goods_voucher.rounding_rule
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setRoundingRule(String roundingRule) {
        this.roundingRule = roundingRule == null ? null : roundingRule.trim();
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method returns the value of the database column tb_goods_voucher.status
     *
     * @return the value of tb_goods_voucher.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method sets the value of the database column tb_goods_voucher.status
     *
     * @param status the value for tb_goods_voucher.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method returns the value of the database column tb_goods_voucher.platform
     *
     * @return the value of tb_goods_voucher.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method sets the value of the database column tb_goods_voucher.platform
     *
     * @param platform the value for tb_goods_voucher.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * 备注 <p/>
     * This method returns the value of the database column tb_goods_voucher.remark
     *
     * @return the value of tb_goods_voucher.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注 <p/>
     * This method sets the value of the database column tb_goods_voucher.remark
     *
     * @param remark the value for tb_goods_voucher.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_voucher.created
     *
     * @return the value of tb_goods_voucher.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_voucher.created
     *
     * @param created the value for tb_goods_voucher.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_voucher.modified
     *
     * @return the value of tb_goods_voucher.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_voucher.modified
     *
     * @param modified the value for tb_goods_voucher.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_goods_voucher.enable_status
     *
     * @return the value of tb_goods_voucher.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_goods_voucher.enable_status
     *
     * @param enableStatus the value for tb_goods_voucher.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}