package com.gcloud.shop.domain;

import java.util.Date;

public class GoodsItem {
    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_goods_item.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long id;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_goods_item.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String storeId;

    /**
     * 商品ID(口碑) <p/>
     * This field corresponds to the database column tb_goods_item.itme_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String itmeId;

    /**
     * 商品ID(系统) <p/>
     * This field corresponds to the database column tb_goods_item.item_sys_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String itemSysId;

    /**
     * 商品类型，券类型填写固定值VOUCHER <p/>
     * This field corresponds to the database column tb_goods_item.item_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String itemType;

    /**
     * 商品名称，请勿超过15个汉字，30个字符 <p/>
     * This field corresponds to the database column tb_goods_item.subject
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String subject;

    /**
     * 商品购买类型 OBTAIN为领取，AUTO_OBTAIN为自动领取 <p/>
     * This field corresponds to the database column tb_goods_item.purchase_mode
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String purchaseMode;

    /**
     * 商品库存数量 <p/>
     * This field corresponds to the database column tb_goods_item.inventory
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long inventory;

    /**
     * 商品首图，尺寸比例在65:53范围内且图片大小不超过10k皆可，图片推荐尺寸540*420 <p/>
     * This field corresponds to the database column tb_goods_item.cover
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String cover;

    /**
     * 商品顺序权重，必须是整数，不传默认为0，权重数值越大排序越靠前 <p/>
     * This field corresponds to the database column tb_goods_item.weight
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long weight;

    /**
     * 商品生效时间，到达生效时间后才可在客户端展示出来。 说明： 商品的生效时间不能早于创建当天的0点 <p/>
     * This field corresponds to the database column tb_goods_item.gmt_start
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date gmtStart;

    /**
     * 商品下架时间，不得早于商品生效时间，商品下架 <p/>
     * This field corresponds to the database column tb_goods_item.gmt_end
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date gmtEnd;

    /**
     * 0否 1是 是否自动延期，默认false。 如果需要设置自动延期，则gmt_start和gmt_end之间要间隔2天以上 <p/>
     * This field corresponds to the database column tb_goods_item.is_auto_expanded
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Byte isAutoExpanded;

    /**
     * 商户通知地址，口碑发消息给商户通知其是否对商品创建、修改、变更状态成功 <p/>
     * This field corresponds to the database column tb_goods_item.operate_notify_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String operateNotifyUrl;

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This field corresponds to the database column tb_goods_item.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Byte status;

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This field corresponds to the database column tb_goods_item.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String platform;

    /**
     * 备注 <p/>
     * This field corresponds to the database column tb_goods_item.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_item.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_item.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_goods_item.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 上架门店id列表，即传入一个或多个shop_id，必须是创建商品partnerId下的店铺，目前支持的店铺最大100个，如果超过100个店铺需要报备 <p/>
     * This field corresponds to the database column tb_goods_item.shop_list
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String shopList;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_goods_item.id
     *
     * @return the value of tb_goods_item.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_goods_item.id
     *
     * @param id the value for tb_goods_item.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_goods_item.store_id
     *
     * @return the value of tb_goods_item.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_goods_item.store_id
     *
     * @param storeId the value for tb_goods_item.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * 商品ID(口碑) <p/>
     * This method returns the value of the database column tb_goods_item.itme_id
     *
     * @return the value of tb_goods_item.itme_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getItmeId() {
        return itmeId;
    }

    /**
     * 商品ID(口碑) <p/>
     * This method sets the value of the database column tb_goods_item.itme_id
     *
     * @param itmeId the value for tb_goods_item.itme_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setItmeId(String itmeId) {
        this.itmeId = itmeId == null ? null : itmeId.trim();
    }

    /**
     * 商品ID(系统) <p/>
     * This method returns the value of the database column tb_goods_item.item_sys_id
     *
     * @return the value of tb_goods_item.item_sys_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getItemSysId() {
        return itemSysId;
    }

    /**
     * 商品ID(系统) <p/>
     * This method sets the value of the database column tb_goods_item.item_sys_id
     *
     * @param itemSysId the value for tb_goods_item.item_sys_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setItemSysId(String itemSysId) {
        this.itemSysId = itemSysId == null ? null : itemSysId.trim();
    }

    /**
     * 商品类型，券类型填写固定值VOUCHER <p/>
     * This method returns the value of the database column tb_goods_item.item_type
     *
     * @return the value of tb_goods_item.item_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * 商品类型，券类型填写固定值VOUCHER <p/>
     * This method sets the value of the database column tb_goods_item.item_type
     *
     * @param itemType the value for tb_goods_item.item_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * 商品名称，请勿超过15个汉字，30个字符 <p/>
     * This method returns the value of the database column tb_goods_item.subject
     *
     * @return the value of tb_goods_item.subject
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getSubject() {
        return subject;
    }

    /**
     * 商品名称，请勿超过15个汉字，30个字符 <p/>
     * This method sets the value of the database column tb_goods_item.subject
     *
     * @param subject the value for tb_goods_item.subject
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * 商品购买类型 OBTAIN为领取，AUTO_OBTAIN为自动领取 <p/>
     * This method returns the value of the database column tb_goods_item.purchase_mode
     *
     * @return the value of tb_goods_item.purchase_mode
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getPurchaseMode() {
        return purchaseMode;
    }

    /**
     * 商品购买类型 OBTAIN为领取，AUTO_OBTAIN为自动领取 <p/>
     * This method sets the value of the database column tb_goods_item.purchase_mode
     *
     * @param purchaseMode the value for tb_goods_item.purchase_mode
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setPurchaseMode(String purchaseMode) {
        this.purchaseMode = purchaseMode == null ? null : purchaseMode.trim();
    }

    /**
     * 商品库存数量 <p/>
     * This method returns the value of the database column tb_goods_item.inventory
     *
     * @return the value of tb_goods_item.inventory
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getInventory() {
        return inventory;
    }

    /**
     * 商品库存数量 <p/>
     * This method sets the value of the database column tb_goods_item.inventory
     *
     * @param inventory the value for tb_goods_item.inventory
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setInventory(Long inventory) {
        this.inventory = inventory;
    }

    /**
     * 商品首图，尺寸比例在65:53范围内且图片大小不超过10k皆可，图片推荐尺寸540*420 <p/>
     * This method returns the value of the database column tb_goods_item.cover
     *
     * @return the value of tb_goods_item.cover
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getCover() {
        return cover;
    }

    /**
     * 商品首图，尺寸比例在65:53范围内且图片大小不超过10k皆可，图片推荐尺寸540*420 <p/>
     * This method sets the value of the database column tb_goods_item.cover
     *
     * @param cover the value for tb_goods_item.cover
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * 商品顺序权重，必须是整数，不传默认为0，权重数值越大排序越靠前 <p/>
     * This method returns the value of the database column tb_goods_item.weight
     *
     * @return the value of tb_goods_item.weight
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getWeight() {
        return weight;
    }

    /**
     * 商品顺序权重，必须是整数，不传默认为0，权重数值越大排序越靠前 <p/>
     * This method sets the value of the database column tb_goods_item.weight
     *
     * @param weight the value for tb_goods_item.weight
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setWeight(Long weight) {
        this.weight = weight;
    }

    /**
     * 商品生效时间，到达生效时间后才可在客户端展示出来。 说明： 商品的生效时间不能早于创建当天的0点 <p/>
     * This method returns the value of the database column tb_goods_item.gmt_start
     *
     * @return the value of tb_goods_item.gmt_start
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getGmtStart() {
        return gmtStart;
    }

    /**
     * 商品生效时间，到达生效时间后才可在客户端展示出来。 说明： 商品的生效时间不能早于创建当天的0点 <p/>
     * This method sets the value of the database column tb_goods_item.gmt_start
     *
     * @param gmtStart the value for tb_goods_item.gmt_start
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setGmtStart(Date gmtStart) {
        this.gmtStart = gmtStart;
    }

    /**
     * 商品下架时间，不得早于商品生效时间，商品下架 <p/>
     * This method returns the value of the database column tb_goods_item.gmt_end
     *
     * @return the value of tb_goods_item.gmt_end
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getGmtEnd() {
        return gmtEnd;
    }

    /**
     * 商品下架时间，不得早于商品生效时间，商品下架 <p/>
     * This method sets the value of the database column tb_goods_item.gmt_end
     *
     * @param gmtEnd the value for tb_goods_item.gmt_end
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setGmtEnd(Date gmtEnd) {
        this.gmtEnd = gmtEnd;
    }

    /**
     * 0否 1是 是否自动延期，默认false。 如果需要设置自动延期，则gmt_start和gmt_end之间要间隔2天以上 <p/>
     * This method returns the value of the database column tb_goods_item.is_auto_expanded
     *
     * @return the value of tb_goods_item.is_auto_expanded
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Byte getIsAutoExpanded() {
        return isAutoExpanded;
    }

    /**
     * 0否 1是 是否自动延期，默认false。 如果需要设置自动延期，则gmt_start和gmt_end之间要间隔2天以上 <p/>
     * This method sets the value of the database column tb_goods_item.is_auto_expanded
     *
     * @param isAutoExpanded the value for tb_goods_item.is_auto_expanded
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setIsAutoExpanded(Byte isAutoExpanded) {
        this.isAutoExpanded = isAutoExpanded;
    }

    /**
     * 商户通知地址，口碑发消息给商户通知其是否对商品创建、修改、变更状态成功 <p/>
     * This method returns the value of the database column tb_goods_item.operate_notify_url
     *
     * @return the value of tb_goods_item.operate_notify_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getOperateNotifyUrl() {
        return operateNotifyUrl;
    }

    /**
     * 商户通知地址，口碑发消息给商户通知其是否对商品创建、修改、变更状态成功 <p/>
     * This method sets the value of the database column tb_goods_item.operate_notify_url
     *
     * @param operateNotifyUrl the value for tb_goods_item.operate_notify_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setOperateNotifyUrl(String operateNotifyUrl) {
        this.operateNotifyUrl = operateNotifyUrl == null ? null : operateNotifyUrl.trim();
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method returns the value of the database column tb_goods_item.status
     *
     * @return the value of tb_goods_item.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method sets the value of the database column tb_goods_item.status
     *
     * @param status the value for tb_goods_item.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method returns the value of the database column tb_goods_item.platform
     *
     * @return the value of tb_goods_item.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method sets the value of the database column tb_goods_item.platform
     *
     * @param platform the value for tb_goods_item.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * 备注 <p/>
     * This method returns the value of the database column tb_goods_item.remark
     *
     * @return the value of tb_goods_item.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注 <p/>
     * This method sets the value of the database column tb_goods_item.remark
     *
     * @param remark the value for tb_goods_item.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_item.created
     *
     * @return the value of tb_goods_item.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_item.created
     *
     * @param created the value for tb_goods_item.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_item.modified
     *
     * @return the value of tb_goods_item.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_item.modified
     *
     * @param modified the value for tb_goods_item.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_goods_item.enable_status
     *
     * @return the value of tb_goods_item.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_goods_item.enable_status
     *
     * @param enableStatus the value for tb_goods_item.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * 上架门店id列表，即传入一个或多个shop_id，必须是创建商品partnerId下的店铺，目前支持的店铺最大100个，如果超过100个店铺需要报备 <p/>
     * This method returns the value of the database column tb_goods_item.shop_list
     *
     * @return the value of tb_goods_item.shop_list
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getShopList() {
        return shopList;
    }

    /**
     * 上架门店id列表，即传入一个或多个shop_id，必须是创建商品partnerId下的店铺，目前支持的店铺最大100个，如果超过100个店铺需要报备 <p/>
     * This method sets the value of the database column tb_goods_item.shop_list
     *
     * @param shopList the value for tb_goods_item.shop_list
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setShopList(String shopList) {
        this.shopList = shopList == null ? null : shopList.trim();
    }
}