package com.gcloud.shop.domain;

import java.util.Date;

public class GoodsSaleRule {
    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_goods_sale_rule.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long id;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_goods_sale_rule.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String storeId;

    /**
     * 商品ID(口碑) <p/>
     * This field corresponds to the database column tb_goods_sale_rule.itme_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String itmeId;

    /**
     * 商品ID(系统) <p/>
     * This field corresponds to the database column tb_goods_sale_rule.item_sys_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String itemSysId;

    /**
     * 可限制商品单日销售上限 <p/>
     * This field corresponds to the database column tb_goods_sale_rule.daily_sales_limit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long dailySalesLimit;

    /**
     * 用户购买策略如不填，则默认值为一个用户一天可以领取三次。 可限制DAY、WEEK、MONTH中n天领取m次，格式为DAY|n|m； 同时也可限制券的1次生命周期中可被领取x次，如ALL|1|x，两个规则可组合使用 <p/>
     * This field corresponds to the database column tb_goods_sale_rule.user_sales_limit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String userSalesLimit;

    /**
     * 购买人群限制集合，开放平台暂时不支持此字段，如果需要使用，需要评估 <p/>
     * This field corresponds to the database column tb_goods_sale_rule.buyer_crowd_limit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String buyerCrowdLimit;

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This field corresponds to the database column tb_goods_sale_rule.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Byte status;

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This field corresponds to the database column tb_goods_sale_rule.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String platform;

    /**
     * 备注 <p/>
     * This field corresponds to the database column tb_goods_sale_rule.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sale_rule.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sale_rule.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_goods_sale_rule.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_goods_sale_rule.id
     *
     * @return the value of tb_goods_sale_rule.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_goods_sale_rule.id
     *
     * @param id the value for tb_goods_sale_rule.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_goods_sale_rule.store_id
     *
     * @return the value of tb_goods_sale_rule.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_goods_sale_rule.store_id
     *
     * @param storeId the value for tb_goods_sale_rule.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * 商品ID(口碑) <p/>
     * This method returns the value of the database column tb_goods_sale_rule.itme_id
     *
     * @return the value of tb_goods_sale_rule.itme_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getItmeId() {
        return itmeId;
    }

    /**
     * 商品ID(口碑) <p/>
     * This method sets the value of the database column tb_goods_sale_rule.itme_id
     *
     * @param itmeId the value for tb_goods_sale_rule.itme_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setItmeId(String itmeId) {
        this.itmeId = itmeId == null ? null : itmeId.trim();
    }

    /**
     * 商品ID(系统) <p/>
     * This method returns the value of the database column tb_goods_sale_rule.item_sys_id
     *
     * @return the value of tb_goods_sale_rule.item_sys_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getItemSysId() {
        return itemSysId;
    }

    /**
     * 商品ID(系统) <p/>
     * This method sets the value of the database column tb_goods_sale_rule.item_sys_id
     *
     * @param itemSysId the value for tb_goods_sale_rule.item_sys_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setItemSysId(String itemSysId) {
        this.itemSysId = itemSysId == null ? null : itemSysId.trim();
    }

    /**
     * 可限制商品单日销售上限 <p/>
     * This method returns the value of the database column tb_goods_sale_rule.daily_sales_limit
     *
     * @return the value of tb_goods_sale_rule.daily_sales_limit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getDailySalesLimit() {
        return dailySalesLimit;
    }

    /**
     * 可限制商品单日销售上限 <p/>
     * This method sets the value of the database column tb_goods_sale_rule.daily_sales_limit
     *
     * @param dailySalesLimit the value for tb_goods_sale_rule.daily_sales_limit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setDailySalesLimit(Long dailySalesLimit) {
        this.dailySalesLimit = dailySalesLimit;
    }

    /**
     * 用户购买策略如不填，则默认值为一个用户一天可以领取三次。 可限制DAY、WEEK、MONTH中n天领取m次，格式为DAY|n|m； 同时也可限制券的1次生命周期中可被领取x次，如ALL|1|x，两个规则可组合使用 <p/>
     * This method returns the value of the database column tb_goods_sale_rule.user_sales_limit
     *
     * @return the value of tb_goods_sale_rule.user_sales_limit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getUserSalesLimit() {
        return userSalesLimit;
    }

    /**
     * 用户购买策略如不填，则默认值为一个用户一天可以领取三次。 可限制DAY、WEEK、MONTH中n天领取m次，格式为DAY|n|m； 同时也可限制券的1次生命周期中可被领取x次，如ALL|1|x，两个规则可组合使用 <p/>
     * This method sets the value of the database column tb_goods_sale_rule.user_sales_limit
     *
     * @param userSalesLimit the value for tb_goods_sale_rule.user_sales_limit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setUserSalesLimit(String userSalesLimit) {
        this.userSalesLimit = userSalesLimit == null ? null : userSalesLimit.trim();
    }

    /**
     * 购买人群限制集合，开放平台暂时不支持此字段，如果需要使用，需要评估 <p/>
     * This method returns the value of the database column tb_goods_sale_rule.buyer_crowd_limit
     *
     * @return the value of tb_goods_sale_rule.buyer_crowd_limit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getBuyerCrowdLimit() {
        return buyerCrowdLimit;
    }

    /**
     * 购买人群限制集合，开放平台暂时不支持此字段，如果需要使用，需要评估 <p/>
     * This method sets the value of the database column tb_goods_sale_rule.buyer_crowd_limit
     *
     * @param buyerCrowdLimit the value for tb_goods_sale_rule.buyer_crowd_limit
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setBuyerCrowdLimit(String buyerCrowdLimit) {
        this.buyerCrowdLimit = buyerCrowdLimit == null ? null : buyerCrowdLimit.trim();
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method returns the value of the database column tb_goods_sale_rule.status
     *
     * @return the value of tb_goods_sale_rule.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method sets the value of the database column tb_goods_sale_rule.status
     *
     * @param status the value for tb_goods_sale_rule.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method returns the value of the database column tb_goods_sale_rule.platform
     *
     * @return the value of tb_goods_sale_rule.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method sets the value of the database column tb_goods_sale_rule.platform
     *
     * @param platform the value for tb_goods_sale_rule.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * 备注 <p/>
     * This method returns the value of the database column tb_goods_sale_rule.remark
     *
     * @return the value of tb_goods_sale_rule.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注 <p/>
     * This method sets the value of the database column tb_goods_sale_rule.remark
     *
     * @param remark the value for tb_goods_sale_rule.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sale_rule.created
     *
     * @return the value of tb_goods_sale_rule.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sale_rule.created
     *
     * @param created the value for tb_goods_sale_rule.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sale_rule.modified
     *
     * @return the value of tb_goods_sale_rule.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sale_rule.modified
     *
     * @param modified the value for tb_goods_sale_rule.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_goods_sale_rule.enable_status
     *
     * @return the value of tb_goods_sale_rule.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_goods_sale_rule.enable_status
     *
     * @param enableStatus the value for tb_goods_sale_rule.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}