package com.gcloud.shop.domain;

import java.util.Date;

public class ShopImage {
    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_shop_image.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long id;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_shop_image.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String storeId;

    /**
     * 图片格式 <p/>
     * This field corresponds to the database column tb_shop_image.image_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String imageType;

    /**
     * 图片名称 <p/>
     * This field corresponds to the database column tb_shop_image.image_name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String imageName;

    /**
     * 图片URL <p/>
     * This field corresponds to the database column tb_shop_image.image_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String imageUrl;

    /**
     * 用于显示指定图片所属的partnerId（支付宝内部使用，外部商户无需填写此字段） <p/>
     * This field corresponds to the database column tb_shop_image.image_pid
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String imagePid;

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This field corresponds to the database column tb_shop_image.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Byte status;

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This field corresponds to the database column tb_shop_image.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String platform;

    /**
     * 备注 <p/>
     * This field corresponds to the database column tb_shop_image.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_image.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_image.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_shop_image.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 图片二进制内容byte[] <p/>
     * This field corresponds to the database column tb_shop_image.image_content
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String imageContent;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_shop_image.id
     *
     * @return the value of tb_shop_image.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_shop_image.id
     *
     * @param id the value for tb_shop_image.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_shop_image.store_id
     *
     * @return the value of tb_shop_image.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_shop_image.store_id
     *
     * @param storeId the value for tb_shop_image.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * 图片格式 <p/>
     * This method returns the value of the database column tb_shop_image.image_type
     *
     * @return the value of tb_shop_image.image_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getImageType() {
        return imageType;
    }

    /**
     * 图片格式 <p/>
     * This method sets the value of the database column tb_shop_image.image_type
     *
     * @param imageType the value for tb_shop_image.image_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setImageType(String imageType) {
        this.imageType = imageType == null ? null : imageType.trim();
    }

    /**
     * 图片名称 <p/>
     * This method returns the value of the database column tb_shop_image.image_name
     *
     * @return the value of tb_shop_image.image_name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * 图片名称 <p/>
     * This method sets the value of the database column tb_shop_image.image_name
     *
     * @param imageName the value for tb_shop_image.image_name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setImageName(String imageName) {
        this.imageName = imageName == null ? null : imageName.trim();
    }

    /**
     * 图片URL <p/>
     * This method returns the value of the database column tb_shop_image.image_url
     *
     * @return the value of tb_shop_image.image_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * 图片URL <p/>
     * This method sets the value of the database column tb_shop_image.image_url
     *
     * @param imageUrl the value for tb_shop_image.image_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * 用于显示指定图片所属的partnerId（支付宝内部使用，外部商户无需填写此字段） <p/>
     * This method returns the value of the database column tb_shop_image.image_pid
     *
     * @return the value of tb_shop_image.image_pid
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getImagePid() {
        return imagePid;
    }

    /**
     * 用于显示指定图片所属的partnerId（支付宝内部使用，外部商户无需填写此字段） <p/>
     * This method sets the value of the database column tb_shop_image.image_pid
     *
     * @param imagePid the value for tb_shop_image.image_pid
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setImagePid(String imagePid) {
        this.imagePid = imagePid == null ? null : imagePid.trim();
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method returns the value of the database column tb_shop_image.status
     *
     * @return the value of tb_shop_image.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method sets the value of the database column tb_shop_image.status
     *
     * @param status the value for tb_shop_image.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method returns the value of the database column tb_shop_image.platform
     *
     * @return the value of tb_shop_image.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method sets the value of the database column tb_shop_image.platform
     *
     * @param platform the value for tb_shop_image.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * 备注 <p/>
     * This method returns the value of the database column tb_shop_image.remark
     *
     * @return the value of tb_shop_image.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注 <p/>
     * This method sets the value of the database column tb_shop_image.remark
     *
     * @param remark the value for tb_shop_image.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_image.created
     *
     * @return the value of tb_shop_image.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_image.created
     *
     * @param created the value for tb_shop_image.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_image.modified
     *
     * @return the value of tb_shop_image.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_image.modified
     *
     * @param modified the value for tb_shop_image.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_shop_image.enable_status
     *
     * @return the value of tb_shop_image.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_shop_image.enable_status
     *
     * @param enableStatus the value for tb_shop_image.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * 图片二进制内容byte[] <p/>
     * This method returns the value of the database column tb_shop_image.image_content
     *
     * @return the value of tb_shop_image.image_content
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getImageContent() {
        return imageContent;
    }

    /**
     * 图片二进制内容byte[] <p/>
     * This method sets the value of the database column tb_shop_image.image_content
     *
     * @param imageContent the value for tb_shop_image.image_content
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setImageContent(String imageContent) {
        this.imageContent = imageContent == null ? null : imageContent.trim();
    }
}