package com.gcloud.shop.domain;

import java.util.Date;

public class ShopWindow {
    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_shop_window.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long id;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_shop_window.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String storeId;

    /**
     * 服务窗名称 <p/>
     * This field corresponds to the database column tb_shop_window.app_name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String appName;

    /**
     * 服务窗头像地址 <p/>
     * This field corresponds to the database column tb_shop_window.logo_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String logoUrl;

    /**
     * 服务窗欢迎语 <p/>
     * This field corresponds to the database column tb_shop_window.public_greeting
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String publicGreeting;

    /**
     * 营业执照地址，建议尺寸 320 x 320px，支持.jpg .jpeg .png 格式，小于3M <p/>
     * This field corresponds to the database column tb_shop_window.license_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String licenseUrl;

    /**
     * 第一张门店照片地址，建议尺寸 320 x 320px，支持.jpg .jpeg .png 格式，小于3M <p/>
     * This field corresponds to the database column tb_shop_window.shop_pic1
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String shopPic1;

    /**
     * 第二张门店照片地址 <p/>
     * This field corresponds to the database column tb_shop_window.shop_pic2
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String shopPic2;

    /**
     * 第三张门店照片地址 <p/>
     * This field corresponds to the database column tb_shop_window.shop_pic3
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String shopPic3;

    /**
     * 授权运营书，企业商户若为被经营方授权，需上传加盖公章的扫描件，请使用照片上传接口上传图片获得image_url <p/>
     * This field corresponds to the database column tb_shop_window.auth_pic
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String authPic;

    /**
     * 门店审核状态，对于系统商而言，只有三个状态，AUDITING：审核中，AUDIT_FAILED：审核驳回，AUDIT_SUCCESS：审核通过。第一次审核通过会触发门店上架 <p/>
     * This field corresponds to the database column tb_shop_window.audit_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String auditStatus;

    /**
     * 门店审核状态描述，如果审核驳回则有相关的驳回理由 <p/>
     * This field corresponds to the database column tb_shop_window.audit_desc
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String auditDesc;

    /**
     * 门店是否上架，T表示上架,F表示未上架，第一次门店审核通过后会触发上架。 <p/>
     * This field corresponds to the database column tb_shop_window.is_online
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String isOnline;

    /**
     * 门店是否在客户端显示，T表示显示，F表示隐藏。 <p/>
     * This field corresponds to the database column tb_shop_window.is_show
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String isShow;

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This field corresponds to the database column tb_shop_window.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String platform;

    /**
     * 备注 <p/>
     * This field corresponds to the database column tb_shop_window.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_window.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_window.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_shop_window.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_shop_window.id
     *
     * @return the value of tb_shop_window.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_shop_window.id
     *
     * @param id the value for tb_shop_window.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_shop_window.store_id
     *
     * @return the value of tb_shop_window.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_shop_window.store_id
     *
     * @param storeId the value for tb_shop_window.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * 服务窗名称 <p/>
     * This method returns the value of the database column tb_shop_window.app_name
     *
     * @return the value of tb_shop_window.app_name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getAppName() {
        return appName;
    }

    /**
     * 服务窗名称 <p/>
     * This method sets the value of the database column tb_shop_window.app_name
     *
     * @param appName the value for tb_shop_window.app_name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * 服务窗头像地址 <p/>
     * This method returns the value of the database column tb_shop_window.logo_url
     *
     * @return the value of tb_shop_window.logo_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * 服务窗头像地址 <p/>
     * This method sets the value of the database column tb_shop_window.logo_url
     *
     * @param logoUrl the value for tb_shop_window.logo_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * 服务窗欢迎语 <p/>
     * This method returns the value of the database column tb_shop_window.public_greeting
     *
     * @return the value of tb_shop_window.public_greeting
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getPublicGreeting() {
        return publicGreeting;
    }

    /**
     * 服务窗欢迎语 <p/>
     * This method sets the value of the database column tb_shop_window.public_greeting
     *
     * @param publicGreeting the value for tb_shop_window.public_greeting
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setPublicGreeting(String publicGreeting) {
        this.publicGreeting = publicGreeting == null ? null : publicGreeting.trim();
    }

    /**
     * 营业执照地址，建议尺寸 320 x 320px，支持.jpg .jpeg .png 格式，小于3M <p/>
     * This method returns the value of the database column tb_shop_window.license_url
     *
     * @return the value of tb_shop_window.license_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getLicenseUrl() {
        return licenseUrl;
    }

    /**
     * 营业执照地址，建议尺寸 320 x 320px，支持.jpg .jpeg .png 格式，小于3M <p/>
     * This method sets the value of the database column tb_shop_window.license_url
     *
     * @param licenseUrl the value for tb_shop_window.license_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setLicenseUrl(String licenseUrl) {
        this.licenseUrl = licenseUrl == null ? null : licenseUrl.trim();
    }

    /**
     * 第一张门店照片地址，建议尺寸 320 x 320px，支持.jpg .jpeg .png 格式，小于3M <p/>
     * This method returns the value of the database column tb_shop_window.shop_pic1
     *
     * @return the value of tb_shop_window.shop_pic1
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getShopPic1() {
        return shopPic1;
    }

    /**
     * 第一张门店照片地址，建议尺寸 320 x 320px，支持.jpg .jpeg .png 格式，小于3M <p/>
     * This method sets the value of the database column tb_shop_window.shop_pic1
     *
     * @param shopPic1 the value for tb_shop_window.shop_pic1
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setShopPic1(String shopPic1) {
        this.shopPic1 = shopPic1 == null ? null : shopPic1.trim();
    }

    /**
     * 第二张门店照片地址 <p/>
     * This method returns the value of the database column tb_shop_window.shop_pic2
     *
     * @return the value of tb_shop_window.shop_pic2
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getShopPic2() {
        return shopPic2;
    }

    /**
     * 第二张门店照片地址 <p/>
     * This method sets the value of the database column tb_shop_window.shop_pic2
     *
     * @param shopPic2 the value for tb_shop_window.shop_pic2
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setShopPic2(String shopPic2) {
        this.shopPic2 = shopPic2 == null ? null : shopPic2.trim();
    }

    /**
     * 第三张门店照片地址 <p/>
     * This method returns the value of the database column tb_shop_window.shop_pic3
     *
     * @return the value of tb_shop_window.shop_pic3
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getShopPic3() {
        return shopPic3;
    }

    /**
     * 第三张门店照片地址 <p/>
     * This method sets the value of the database column tb_shop_window.shop_pic3
     *
     * @param shopPic3 the value for tb_shop_window.shop_pic3
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setShopPic3(String shopPic3) {
        this.shopPic3 = shopPic3 == null ? null : shopPic3.trim();
    }

    /**
     * 授权运营书，企业商户若为被经营方授权，需上传加盖公章的扫描件，请使用照片上传接口上传图片获得image_url <p/>
     * This method returns the value of the database column tb_shop_window.auth_pic
     *
     * @return the value of tb_shop_window.auth_pic
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getAuthPic() {
        return authPic;
    }

    /**
     * 授权运营书，企业商户若为被经营方授权，需上传加盖公章的扫描件，请使用照片上传接口上传图片获得image_url <p/>
     * This method sets the value of the database column tb_shop_window.auth_pic
     *
     * @param authPic the value for tb_shop_window.auth_pic
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setAuthPic(String authPic) {
        this.authPic = authPic == null ? null : authPic.trim();
    }

    /**
     * 门店审核状态，对于系统商而言，只有三个状态，AUDITING：审核中，AUDIT_FAILED：审核驳回，AUDIT_SUCCESS：审核通过。第一次审核通过会触发门店上架 <p/>
     * This method returns the value of the database column tb_shop_window.audit_status
     *
     * @return the value of tb_shop_window.audit_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * 门店审核状态，对于系统商而言，只有三个状态，AUDITING：审核中，AUDIT_FAILED：审核驳回，AUDIT_SUCCESS：审核通过。第一次审核通过会触发门店上架 <p/>
     * This method sets the value of the database column tb_shop_window.audit_status
     *
     * @param auditStatus the value for tb_shop_window.audit_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }

    /**
     * 门店审核状态描述，如果审核驳回则有相关的驳回理由 <p/>
     * This method returns the value of the database column tb_shop_window.audit_desc
     *
     * @return the value of tb_shop_window.audit_desc
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getAuditDesc() {
        return auditDesc;
    }

    /**
     * 门店审核状态描述，如果审核驳回则有相关的驳回理由 <p/>
     * This method sets the value of the database column tb_shop_window.audit_desc
     *
     * @param auditDesc the value for tb_shop_window.audit_desc
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setAuditDesc(String auditDesc) {
        this.auditDesc = auditDesc == null ? null : auditDesc.trim();
    }

    /**
     * 门店是否上架，T表示上架,F表示未上架，第一次门店审核通过后会触发上架。 <p/>
     * This method returns the value of the database column tb_shop_window.is_online
     *
     * @return the value of tb_shop_window.is_online
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getIsOnline() {
        return isOnline;
    }

    /**
     * 门店是否上架，T表示上架,F表示未上架，第一次门店审核通过后会触发上架。 <p/>
     * This method sets the value of the database column tb_shop_window.is_online
     *
     * @param isOnline the value for tb_shop_window.is_online
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setIsOnline(String isOnline) {
        this.isOnline = isOnline == null ? null : isOnline.trim();
    }

    /**
     * 门店是否在客户端显示，T表示显示，F表示隐藏。 <p/>
     * This method returns the value of the database column tb_shop_window.is_show
     *
     * @return the value of tb_shop_window.is_show
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * 门店是否在客户端显示，T表示显示，F表示隐藏。 <p/>
     * This method sets the value of the database column tb_shop_window.is_show
     *
     * @param isShow the value for tb_shop_window.is_show
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method returns the value of the database column tb_shop_window.platform
     *
     * @return the value of tb_shop_window.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method sets the value of the database column tb_shop_window.platform
     *
     * @param platform the value for tb_shop_window.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * 备注 <p/>
     * This method returns the value of the database column tb_shop_window.remark
     *
     * @return the value of tb_shop_window.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注 <p/>
     * This method sets the value of the database column tb_shop_window.remark
     *
     * @param remark the value for tb_shop_window.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_window.created
     *
     * @return the value of tb_shop_window.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_window.created
     *
     * @param created the value for tb_shop_window.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_window.modified
     *
     * @return the value of tb_shop_window.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_window.modified
     *
     * @param modified the value for tb_shop_window.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_shop_window.enable_status
     *
     * @return the value of tb_shop_window.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_shop_window.enable_status
     *
     * @param enableStatus the value for tb_shop_window.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}