package com.gcloud.shop.domain;

import java.util.Date;

public class ShopMenu {
    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_shop_menu.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long id;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_shop_menu.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String storeId;

    /**
     * 菜单信息 <p/>
     * This field corresponds to the database column tb_shop_menu.menu
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String menu;

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This field corresponds to the database column tb_shop_menu.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Byte status;

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This field corresponds to the database column tb_shop_menu.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String platform;

    /**
     * 备注 <p/>
     * This field corresponds to the database column tb_shop_menu.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_menu.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_menu.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_shop_menu.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_shop_menu.id
     *
     * @return the value of tb_shop_menu.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_shop_menu.id
     *
     * @param id the value for tb_shop_menu.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_shop_menu.store_id
     *
     * @return the value of tb_shop_menu.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_shop_menu.store_id
     *
     * @param storeId the value for tb_shop_menu.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * 菜单信息 <p/>
     * This method returns the value of the database column tb_shop_menu.menu
     *
     * @return the value of tb_shop_menu.menu
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getMenu() {
        return menu;
    }

    /**
     * 菜单信息 <p/>
     * This method sets the value of the database column tb_shop_menu.menu
     *
     * @param menu the value for tb_shop_menu.menu
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setMenu(String menu) {
        this.menu = menu == null ? null : menu.trim();
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method returns the value of the database column tb_shop_menu.status
     *
     * @return the value of tb_shop_menu.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method sets the value of the database column tb_shop_menu.status
     *
     * @param status the value for tb_shop_menu.status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method returns the value of the database column tb_shop_menu.platform
     *
     * @return the value of tb_shop_menu.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * 平台信息(kb口碑 tb淘宝 bd百度外卖) <p/>
     * This method sets the value of the database column tb_shop_menu.platform
     *
     * @param platform the value for tb_shop_menu.platform
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * 备注 <p/>
     * This method returns the value of the database column tb_shop_menu.remark
     *
     * @return the value of tb_shop_menu.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注 <p/>
     * This method sets the value of the database column tb_shop_menu.remark
     *
     * @param remark the value for tb_shop_menu.remark
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_menu.created
     *
     * @return the value of tb_shop_menu.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_menu.created
     *
     * @param created the value for tb_shop_menu.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_menu.modified
     *
     * @return the value of tb_shop_menu.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_menu.modified
     *
     * @param modified the value for tb_shop_menu.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_shop_menu.enable_status
     *
     * @return the value of tb_shop_menu.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_shop_menu.enable_status
     *
     * @param enableStatus the value for tb_shop_menu.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}