package com.gcloud.shop.domain;

import java.util.Date;

public class TradeInfo {
    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_trade_info.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long id;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_trade_info.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String storeId;

    /**
     * 商户订单号,64个字符以内、只能包含字母、数字、下划线；需保证在商户端不重复 <p/>
     * This field corresponds to the database column tb_trade_info.out_trade_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String outTradeNo;

    /**
     * 卖家支付宝用户ID。 如果该值为空，则默认为商户签约账号对应的支付宝用户ID <p/>
     * This field corresponds to the database column tb_trade_info.seller_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String sellerId;

    /**
     * 订单总金额，单位为元，精确到小数点后两位，取值范围[0.01,100000000] <p/>
     * This field corresponds to the database column tb_trade_info.total_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Double totalAmount;

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This field corresponds to the database column tb_trade_info.discountable_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Double discountableAmount;

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This field corresponds to the database column tb_trade_info.undiscountable_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Double undiscountableAmount;

    /**
     * 买家支付宝账号，和buyer_id不能同时为空 <p/>
     * This field corresponds to the database column tb_trade_info.buyer_logon_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String buyerLogonId;

    /**
     * 订单标题 <p/>
     * This field corresponds to the database column tb_trade_info.subject
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String subject;

    /**
     * 对交易或商品的描述 <p/>
     * This field corresponds to the database column tb_trade_info.body
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String body;

    /**
     * 买家的支付宝唯一用户号（2088开头的16位纯数字）,和buyer_logon_id不能同时为空 <p/>
     * This field corresponds to the database column tb_trade_info.buyer_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String buyerId;

    /**
     * 商户操作员编号 <p/>
     * This field corresponds to the database column tb_trade_info.operator_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String operatorId;

    /**
     * 商户机具终端编号 <p/>
     * This field corresponds to the database column tb_trade_info.terminal_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String terminalId;

    /**
     * 该笔订单允许的最晚付款时间，逾期将关闭交易。取值范围：1m～15d。m-分钟，h-小时，d-天，1c-当天（1c-当天的情况下，无论交易何时创建，都在0点关闭）。 该参数数值不接受小数点， 如 1.5h，可转换为 90m。 <p/>
     * This field corresponds to the database column tb_trade_info.timeout_express
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String timeoutExpress;

    /**
     * 支付宝的店铺编号 <p/>
     * This field corresponds to the database column tb_trade_info.alipay_store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String alipayStoreId;

    /**
     * 二级商户的支付宝id  <p/>
     * This field corresponds to the database column tb_trade_info.merchant_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String merchantId;

    /**
     * 系统商编号 该参数作为系统商返佣数据提取的依据，请填写系统商签约协议的PID <p/>
     * This field corresponds to the database column tb_trade_info.sys_service_provider_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String sysServiceProviderId;

    /**
     * 使用花呗分期要进行的分期数 <p/>
     * This field corresponds to the database column tb_trade_info.hb_fq_num
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String hbFqNum;

    /**
     * 使用花呗分期需要卖家承担的手续费比例的百分值，传入100代表100% <p/>
     * This field corresponds to the database column tb_trade_info.hb_fq_seller_percent
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String hbFqSellerPercent;

    /**
     * 分账类型 卖家的分账类型，目前只支持传入ROYALTY（普通分账类型）。 <p/>
     * This field corresponds to the database column tb_trade_info.royalty_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String royaltyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_info.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_info.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_trade_info.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_trade_info.id
     *
     * @return the value of tb_trade_info.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_trade_info.id
     *
     * @param id the value for tb_trade_info.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_trade_info.store_id
     *
     * @return the value of tb_trade_info.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_trade_info.store_id
     *
     * @param storeId the value for tb_trade_info.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * 商户订单号,64个字符以内、只能包含字母、数字、下划线；需保证在商户端不重复 <p/>
     * This method returns the value of the database column tb_trade_info.out_trade_no
     *
     * @return the value of tb_trade_info.out_trade_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * 商户订单号,64个字符以内、只能包含字母、数字、下划线；需保证在商户端不重复 <p/>
     * This method sets the value of the database column tb_trade_info.out_trade_no
     *
     * @param outTradeNo the value for tb_trade_info.out_trade_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * 卖家支付宝用户ID。 如果该值为空，则默认为商户签约账号对应的支付宝用户ID <p/>
     * This method returns the value of the database column tb_trade_info.seller_id
     *
     * @return the value of tb_trade_info.seller_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * 卖家支付宝用户ID。 如果该值为空，则默认为商户签约账号对应的支付宝用户ID <p/>
     * This method sets the value of the database column tb_trade_info.seller_id
     *
     * @param sellerId the value for tb_trade_info.seller_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * 订单总金额，单位为元，精确到小数点后两位，取值范围[0.01,100000000] <p/>
     * This method returns the value of the database column tb_trade_info.total_amount
     *
     * @return the value of tb_trade_info.total_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Double getTotalAmount() {
        return totalAmount;
    }

    /**
     * 订单总金额，单位为元，精确到小数点后两位，取值范围[0.01,100000000] <p/>
     * This method sets the value of the database column tb_trade_info.total_amount
     *
     * @param totalAmount the value for tb_trade_info.total_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This method returns the value of the database column tb_trade_info.discountable_amount
     *
     * @return the value of tb_trade_info.discountable_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Double getDiscountableAmount() {
        return discountableAmount;
    }

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This method sets the value of the database column tb_trade_info.discountable_amount
     *
     * @param discountableAmount the value for tb_trade_info.discountable_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setDiscountableAmount(Double discountableAmount) {
        this.discountableAmount = discountableAmount;
    }

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This method returns the value of the database column tb_trade_info.undiscountable_amount
     *
     * @return the value of tb_trade_info.undiscountable_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Double getUndiscountableAmount() {
        return undiscountableAmount;
    }

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This method sets the value of the database column tb_trade_info.undiscountable_amount
     *
     * @param undiscountableAmount the value for tb_trade_info.undiscountable_amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setUndiscountableAmount(Double undiscountableAmount) {
        this.undiscountableAmount = undiscountableAmount;
    }

    /**
     * 买家支付宝账号，和buyer_id不能同时为空 <p/>
     * This method returns the value of the database column tb_trade_info.buyer_logon_id
     *
     * @return the value of tb_trade_info.buyer_logon_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getBuyerLogonId() {
        return buyerLogonId;
    }

    /**
     * 买家支付宝账号，和buyer_id不能同时为空 <p/>
     * This method sets the value of the database column tb_trade_info.buyer_logon_id
     *
     * @param buyerLogonId the value for tb_trade_info.buyer_logon_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setBuyerLogonId(String buyerLogonId) {
        this.buyerLogonId = buyerLogonId == null ? null : buyerLogonId.trim();
    }

    /**
     * 订单标题 <p/>
     * This method returns the value of the database column tb_trade_info.subject
     *
     * @return the value of tb_trade_info.subject
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getSubject() {
        return subject;
    }

    /**
     * 订单标题 <p/>
     * This method sets the value of the database column tb_trade_info.subject
     *
     * @param subject the value for tb_trade_info.subject
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * 对交易或商品的描述 <p/>
     * This method returns the value of the database column tb_trade_info.body
     *
     * @return the value of tb_trade_info.body
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getBody() {
        return body;
    }

    /**
     * 对交易或商品的描述 <p/>
     * This method sets the value of the database column tb_trade_info.body
     *
     * @param body the value for tb_trade_info.body
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * 买家的支付宝唯一用户号（2088开头的16位纯数字）,和buyer_logon_id不能同时为空 <p/>
     * This method returns the value of the database column tb_trade_info.buyer_id
     *
     * @return the value of tb_trade_info.buyer_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * 买家的支付宝唯一用户号（2088开头的16位纯数字）,和buyer_logon_id不能同时为空 <p/>
     * This method sets the value of the database column tb_trade_info.buyer_id
     *
     * @param buyerId the value for tb_trade_info.buyer_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId == null ? null : buyerId.trim();
    }

    /**
     * 商户操作员编号 <p/>
     * This method returns the value of the database column tb_trade_info.operator_id
     *
     * @return the value of tb_trade_info.operator_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * 商户操作员编号 <p/>
     * This method sets the value of the database column tb_trade_info.operator_id
     *
     * @param operatorId the value for tb_trade_info.operator_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * 商户机具终端编号 <p/>
     * This method returns the value of the database column tb_trade_info.terminal_id
     *
     * @return the value of tb_trade_info.terminal_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getTerminalId() {
        return terminalId;
    }

    /**
     * 商户机具终端编号 <p/>
     * This method sets the value of the database column tb_trade_info.terminal_id
     *
     * @param terminalId the value for tb_trade_info.terminal_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId == null ? null : terminalId.trim();
    }

    /**
     * 该笔订单允许的最晚付款时间，逾期将关闭交易。取值范围：1m～15d。m-分钟，h-小时，d-天，1c-当天（1c-当天的情况下，无论交易何时创建，都在0点关闭）。 该参数数值不接受小数点， 如 1.5h，可转换为 90m。 <p/>
     * This method returns the value of the database column tb_trade_info.timeout_express
     *
     * @return the value of tb_trade_info.timeout_express
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getTimeoutExpress() {
        return timeoutExpress;
    }

    /**
     * 该笔订单允许的最晚付款时间，逾期将关闭交易。取值范围：1m～15d。m-分钟，h-小时，d-天，1c-当天（1c-当天的情况下，无论交易何时创建，都在0点关闭）。 该参数数值不接受小数点， 如 1.5h，可转换为 90m。 <p/>
     * This method sets the value of the database column tb_trade_info.timeout_express
     *
     * @param timeoutExpress the value for tb_trade_info.timeout_express
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setTimeoutExpress(String timeoutExpress) {
        this.timeoutExpress = timeoutExpress == null ? null : timeoutExpress.trim();
    }

    /**
     * 支付宝的店铺编号 <p/>
     * This method returns the value of the database column tb_trade_info.alipay_store_id
     *
     * @return the value of tb_trade_info.alipay_store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getAlipayStoreId() {
        return alipayStoreId;
    }

    /**
     * 支付宝的店铺编号 <p/>
     * This method sets the value of the database column tb_trade_info.alipay_store_id
     *
     * @param alipayStoreId the value for tb_trade_info.alipay_store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setAlipayStoreId(String alipayStoreId) {
        this.alipayStoreId = alipayStoreId == null ? null : alipayStoreId.trim();
    }

    /**
     * 二级商户的支付宝id  <p/>
     * This method returns the value of the database column tb_trade_info.merchant_id
     *
     * @return the value of tb_trade_info.merchant_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * 二级商户的支付宝id  <p/>
     * This method sets the value of the database column tb_trade_info.merchant_id
     *
     * @param merchantId the value for tb_trade_info.merchant_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * 系统商编号 该参数作为系统商返佣数据提取的依据，请填写系统商签约协议的PID <p/>
     * This method returns the value of the database column tb_trade_info.sys_service_provider_id
     *
     * @return the value of tb_trade_info.sys_service_provider_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getSysServiceProviderId() {
        return sysServiceProviderId;
    }

    /**
     * 系统商编号 该参数作为系统商返佣数据提取的依据，请填写系统商签约协议的PID <p/>
     * This method sets the value of the database column tb_trade_info.sys_service_provider_id
     *
     * @param sysServiceProviderId the value for tb_trade_info.sys_service_provider_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setSysServiceProviderId(String sysServiceProviderId) {
        this.sysServiceProviderId = sysServiceProviderId == null ? null : sysServiceProviderId.trim();
    }

    /**
     * 使用花呗分期要进行的分期数 <p/>
     * This method returns the value of the database column tb_trade_info.hb_fq_num
     *
     * @return the value of tb_trade_info.hb_fq_num
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getHbFqNum() {
        return hbFqNum;
    }

    /**
     * 使用花呗分期要进行的分期数 <p/>
     * This method sets the value of the database column tb_trade_info.hb_fq_num
     *
     * @param hbFqNum the value for tb_trade_info.hb_fq_num
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setHbFqNum(String hbFqNum) {
        this.hbFqNum = hbFqNum == null ? null : hbFqNum.trim();
    }

    /**
     * 使用花呗分期需要卖家承担的手续费比例的百分值，传入100代表100% <p/>
     * This method returns the value of the database column tb_trade_info.hb_fq_seller_percent
     *
     * @return the value of tb_trade_info.hb_fq_seller_percent
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getHbFqSellerPercent() {
        return hbFqSellerPercent;
    }

    /**
     * 使用花呗分期需要卖家承担的手续费比例的百分值，传入100代表100% <p/>
     * This method sets the value of the database column tb_trade_info.hb_fq_seller_percent
     *
     * @param hbFqSellerPercent the value for tb_trade_info.hb_fq_seller_percent
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setHbFqSellerPercent(String hbFqSellerPercent) {
        this.hbFqSellerPercent = hbFqSellerPercent == null ? null : hbFqSellerPercent.trim();
    }

    /**
     * 分账类型 卖家的分账类型，目前只支持传入ROYALTY（普通分账类型）。 <p/>
     * This method returns the value of the database column tb_trade_info.royalty_type
     *
     * @return the value of tb_trade_info.royalty_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getRoyaltyType() {
        return royaltyType;
    }

    /**
     * 分账类型 卖家的分账类型，目前只支持传入ROYALTY（普通分账类型）。 <p/>
     * This method sets the value of the database column tb_trade_info.royalty_type
     *
     * @param royaltyType the value for tb_trade_info.royalty_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setRoyaltyType(String royaltyType) {
        this.royaltyType = royaltyType == null ? null : royaltyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_info.created
     *
     * @return the value of tb_trade_info.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_info.created
     *
     * @param created the value for tb_trade_info.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_info.modified
     *
     * @return the value of tb_trade_info.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_info.modified
     *
     * @param modified the value for tb_trade_info.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_trade_info.enable_status
     *
     * @return the value of tb_trade_info.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_trade_info.enable_status
     *
     * @param enableStatus the value for tb_trade_info.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}