package com.gcloud.shop.domain;

import java.util.Date;

public class TradeRoyalty {
    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_trade_royalty.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long id;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_trade_royalty.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String storeId;

    /**
     * 商户订单号,64个字符以内、只能包含字母、数字、下划线；需保证在商户端不重复 <p/>
     * This field corresponds to the database column tb_trade_royalty.out_trade_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String outTradeNo;

    /**
     * 分账序列号，表示分账执行的顺序，必须为正整数  <p/>
     * This field corresponds to the database column tb_trade_royalty.serial_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String serialNo;

    /**
     * 分账批次号。 目前需要和转入账号类型为bankIndex配合使用。 <p/>
     * This field corresponds to the database column tb_trade_royalty.batch_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String batchNo;

    /**
     * 接受分账金额的账户类型 <p/>
     * This field corresponds to the database column tb_trade_royalty.trans_in_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String transInType;

    /**
     * 商户分账的外部关联号，用于关联到每一笔分账信息，商户需保证其唯一性。 如果为空，该值则默认为“商户网站唯一订单号+分账序列号” <p/>
     * This field corresponds to the database column tb_trade_royalty.out_relation_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String outRelationId;

    /**
     * 要分账的账户类型。 目前只支持userId：支付宝账号对应的支付宝唯一用户号。 默认值为userId。  <p/>
     * This field corresponds to the database column tb_trade_royalty.trans_out_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String transOutType;

    /**
     * 如果转出账号类型为userId，本参数为要分账的支付宝账号对应的支付宝唯一用户号。以2088开头的纯16位数字。  <p/>
     * This field corresponds to the database column tb_trade_royalty.trans_out
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String transOut;

    /**
     * 如果转入账号类型为userId，本参数为接受分账金额的支付宝账号对应的支付宝唯一用户号。以2088开头的纯16位数字。  如果转入账号类型为bankIndex，本参数为28位的银行编号（商户和支付宝签约时确定）。 如果转入账号类型为storeId，本参数为商户的门店ID。  <p/>
     * This field corresponds to the database column tb_trade_royalty.trans_in
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String transIn;

    /**
     * 分账的金额，单位为元  <p/>
     * This field corresponds to the database column tb_trade_royalty.amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Double amount;

    /**
     * 分账描述信息  <p/>
     * This field corresponds to the database column tb_trade_royalty.desc
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String desc;

    /**
     * 分账的比例，值为20代表按20%的比例分账  <p/>
     * This field corresponds to the database column tb_trade_royalty.amount_percentage
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String amountPercentage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_royalty.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_royalty.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_trade_royalty.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_trade_royalty.id
     *
     * @return the value of tb_trade_royalty.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_trade_royalty.id
     *
     * @param id the value for tb_trade_royalty.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_trade_royalty.store_id
     *
     * @return the value of tb_trade_royalty.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_trade_royalty.store_id
     *
     * @param storeId the value for tb_trade_royalty.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * 商户订单号,64个字符以内、只能包含字母、数字、下划线；需保证在商户端不重复 <p/>
     * This method returns the value of the database column tb_trade_royalty.out_trade_no
     *
     * @return the value of tb_trade_royalty.out_trade_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * 商户订单号,64个字符以内、只能包含字母、数字、下划线；需保证在商户端不重复 <p/>
     * This method sets the value of the database column tb_trade_royalty.out_trade_no
     *
     * @param outTradeNo the value for tb_trade_royalty.out_trade_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * 分账序列号，表示分账执行的顺序，必须为正整数  <p/>
     * This method returns the value of the database column tb_trade_royalty.serial_no
     *
     * @return the value of tb_trade_royalty.serial_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * 分账序列号，表示分账执行的顺序，必须为正整数  <p/>
     * This method sets the value of the database column tb_trade_royalty.serial_no
     *
     * @param serialNo the value for tb_trade_royalty.serial_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * 分账批次号。 目前需要和转入账号类型为bankIndex配合使用。 <p/>
     * This method returns the value of the database column tb_trade_royalty.batch_no
     *
     * @return the value of tb_trade_royalty.batch_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * 分账批次号。 目前需要和转入账号类型为bankIndex配合使用。 <p/>
     * This method sets the value of the database column tb_trade_royalty.batch_no
     *
     * @param batchNo the value for tb_trade_royalty.batch_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * 接受分账金额的账户类型 <p/>
     * This method returns the value of the database column tb_trade_royalty.trans_in_type
     *
     * @return the value of tb_trade_royalty.trans_in_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getTransInType() {
        return transInType;
    }

    /**
     * 接受分账金额的账户类型 <p/>
     * This method sets the value of the database column tb_trade_royalty.trans_in_type
     *
     * @param transInType the value for tb_trade_royalty.trans_in_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setTransInType(String transInType) {
        this.transInType = transInType == null ? null : transInType.trim();
    }

    /**
     * 商户分账的外部关联号，用于关联到每一笔分账信息，商户需保证其唯一性。 如果为空，该值则默认为“商户网站唯一订单号+分账序列号” <p/>
     * This method returns the value of the database column tb_trade_royalty.out_relation_id
     *
     * @return the value of tb_trade_royalty.out_relation_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getOutRelationId() {
        return outRelationId;
    }

    /**
     * 商户分账的外部关联号，用于关联到每一笔分账信息，商户需保证其唯一性。 如果为空，该值则默认为“商户网站唯一订单号+分账序列号” <p/>
     * This method sets the value of the database column tb_trade_royalty.out_relation_id
     *
     * @param outRelationId the value for tb_trade_royalty.out_relation_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setOutRelationId(String outRelationId) {
        this.outRelationId = outRelationId == null ? null : outRelationId.trim();
    }

    /**
     * 要分账的账户类型。 目前只支持userId：支付宝账号对应的支付宝唯一用户号。 默认值为userId。  <p/>
     * This method returns the value of the database column tb_trade_royalty.trans_out_type
     *
     * @return the value of tb_trade_royalty.trans_out_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getTransOutType() {
        return transOutType;
    }

    /**
     * 要分账的账户类型。 目前只支持userId：支付宝账号对应的支付宝唯一用户号。 默认值为userId。  <p/>
     * This method sets the value of the database column tb_trade_royalty.trans_out_type
     *
     * @param transOutType the value for tb_trade_royalty.trans_out_type
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setTransOutType(String transOutType) {
        this.transOutType = transOutType == null ? null : transOutType.trim();
    }

    /**
     * 如果转出账号类型为userId，本参数为要分账的支付宝账号对应的支付宝唯一用户号。以2088开头的纯16位数字。  <p/>
     * This method returns the value of the database column tb_trade_royalty.trans_out
     *
     * @return the value of tb_trade_royalty.trans_out
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getTransOut() {
        return transOut;
    }

    /**
     * 如果转出账号类型为userId，本参数为要分账的支付宝账号对应的支付宝唯一用户号。以2088开头的纯16位数字。  <p/>
     * This method sets the value of the database column tb_trade_royalty.trans_out
     *
     * @param transOut the value for tb_trade_royalty.trans_out
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setTransOut(String transOut) {
        this.transOut = transOut == null ? null : transOut.trim();
    }

    /**
     * 如果转入账号类型为userId，本参数为接受分账金额的支付宝账号对应的支付宝唯一用户号。以2088开头的纯16位数字。  如果转入账号类型为bankIndex，本参数为28位的银行编号（商户和支付宝签约时确定）。 如果转入账号类型为storeId，本参数为商户的门店ID。  <p/>
     * This method returns the value of the database column tb_trade_royalty.trans_in
     *
     * @return the value of tb_trade_royalty.trans_in
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getTransIn() {
        return transIn;
    }

    /**
     * 如果转入账号类型为userId，本参数为接受分账金额的支付宝账号对应的支付宝唯一用户号。以2088开头的纯16位数字。  如果转入账号类型为bankIndex，本参数为28位的银行编号（商户和支付宝签约时确定）。 如果转入账号类型为storeId，本参数为商户的门店ID。  <p/>
     * This method sets the value of the database column tb_trade_royalty.trans_in
     *
     * @param transIn the value for tb_trade_royalty.trans_in
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setTransIn(String transIn) {
        this.transIn = transIn == null ? null : transIn.trim();
    }

    /**
     * 分账的金额，单位为元  <p/>
     * This method returns the value of the database column tb_trade_royalty.amount
     *
     * @return the value of tb_trade_royalty.amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * 分账的金额，单位为元  <p/>
     * This method sets the value of the database column tb_trade_royalty.amount
     *
     * @param amount the value for tb_trade_royalty.amount
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * 分账描述信息  <p/>
     * This method returns the value of the database column tb_trade_royalty.desc
     *
     * @return the value of tb_trade_royalty.desc
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getDesc() {
        return desc;
    }

    /**
     * 分账描述信息  <p/>
     * This method sets the value of the database column tb_trade_royalty.desc
     *
     * @param desc the value for tb_trade_royalty.desc
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * 分账的比例，值为20代表按20%的比例分账  <p/>
     * This method returns the value of the database column tb_trade_royalty.amount_percentage
     *
     * @return the value of tb_trade_royalty.amount_percentage
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getAmountPercentage() {
        return amountPercentage;
    }

    /**
     * 分账的比例，值为20代表按20%的比例分账  <p/>
     * This method sets the value of the database column tb_trade_royalty.amount_percentage
     *
     * @param amountPercentage the value for tb_trade_royalty.amount_percentage
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setAmountPercentage(String amountPercentage) {
        this.amountPercentage = amountPercentage == null ? null : amountPercentage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_royalty.created
     *
     * @return the value of tb_trade_royalty.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_royalty.created
     *
     * @param created the value for tb_trade_royalty.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_royalty.modified
     *
     * @return the value of tb_trade_royalty.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_royalty.modified
     *
     * @param modified the value for tb_trade_royalty.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_trade_royalty.enable_status
     *
     * @return the value of tb_trade_royalty.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_trade_royalty.enable_status
     *
     * @param enableStatus the value for tb_trade_royalty.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}