package com.gcloud.shop.domain;

import java.util.Date;

public class TradeDetail {
    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_trade_detail.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long id;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_trade_detail.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String storeId;

    /**
     * 商户订单号,64个字符以内、只能包含字母、数字、下划线；需保证在商户端不重复 <p/>
     * This field corresponds to the database column tb_trade_detail.out_trade_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String outTradeNo;

    /**
     * 卖家支付宝用户ID。 如果该值为空，则默认为商户签约账号对应的支付宝用户ID <p/>
     * This field corresponds to the database column tb_trade_detail.goods_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String goodsId;

    /**
     * 订单总金额，单位为元，精确到小数点后两位，取值范围[0.01,100000000] <p/>
     * This field corresponds to the database column tb_trade_detail.alipay_goods_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String alipayGoodsId;

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This field corresponds to the database column tb_trade_detail.goods_name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String goodsName;

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This field corresponds to the database column tb_trade_detail.quantity
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Long quantity;

    /**
     * 买家支付宝账号，和buyer_id不能同时为空 <p/>
     * This field corresponds to the database column tb_trade_detail.price
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Double price;

    /**
     * 订单标题 <p/>
     * This field corresponds to the database column tb_trade_detail.goods_category
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String goodsCategory;

    /**
     * 对交易或商品的描述 <p/>
     * This field corresponds to the database column tb_trade_detail.body
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String body;

    /**
     * 买家的支付宝唯一用户号（2088开头的16位纯数字）,和buyer_logon_id不能同时为空 <p/>
     * This field corresponds to the database column tb_trade_detail.show_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private String showUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_detail.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_detail.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_trade_detail.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_trade_detail.id
     *
     * @return the value of tb_trade_detail.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_trade_detail.id
     *
     * @param id the value for tb_trade_detail.id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_trade_detail.store_id
     *
     * @return the value of tb_trade_detail.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_trade_detail.store_id
     *
     * @param storeId the value for tb_trade_detail.store_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * 商户订单号,64个字符以内、只能包含字母、数字、下划线；需保证在商户端不重复 <p/>
     * This method returns the value of the database column tb_trade_detail.out_trade_no
     *
     * @return the value of tb_trade_detail.out_trade_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * 商户订单号,64个字符以内、只能包含字母、数字、下划线；需保证在商户端不重复 <p/>
     * This method sets the value of the database column tb_trade_detail.out_trade_no
     *
     * @param outTradeNo the value for tb_trade_detail.out_trade_no
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * 卖家支付宝用户ID。 如果该值为空，则默认为商户签约账号对应的支付宝用户ID <p/>
     * This method returns the value of the database column tb_trade_detail.goods_id
     *
     * @return the value of tb_trade_detail.goods_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * 卖家支付宝用户ID。 如果该值为空，则默认为商户签约账号对应的支付宝用户ID <p/>
     * This method sets the value of the database column tb_trade_detail.goods_id
     *
     * @param goodsId the value for tb_trade_detail.goods_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * 订单总金额，单位为元，精确到小数点后两位，取值范围[0.01,100000000] <p/>
     * This method returns the value of the database column tb_trade_detail.alipay_goods_id
     *
     * @return the value of tb_trade_detail.alipay_goods_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getAlipayGoodsId() {
        return alipayGoodsId;
    }

    /**
     * 订单总金额，单位为元，精确到小数点后两位，取值范围[0.01,100000000] <p/>
     * This method sets the value of the database column tb_trade_detail.alipay_goods_id
     *
     * @param alipayGoodsId the value for tb_trade_detail.alipay_goods_id
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setAlipayGoodsId(String alipayGoodsId) {
        this.alipayGoodsId = alipayGoodsId == null ? null : alipayGoodsId.trim();
    }

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This method returns the value of the database column tb_trade_detail.goods_name
     *
     * @return the value of tb_trade_detail.goods_name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This method sets the value of the database column tb_trade_detail.goods_name
     *
     * @param goodsName the value for tb_trade_detail.goods_name
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This method returns the value of the database column tb_trade_detail.quantity
     *
     * @return the value of tb_trade_detail.quantity
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * 可打折金额. 参与优惠计算的金额，单位为元，精确到小数点后两位 <p/>
     * This method sets the value of the database column tb_trade_detail.quantity
     *
     * @param quantity the value for tb_trade_detail.quantity
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * 买家支付宝账号，和buyer_id不能同时为空 <p/>
     * This method returns the value of the database column tb_trade_detail.price
     *
     * @return the value of tb_trade_detail.price
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * 买家支付宝账号，和buyer_id不能同时为空 <p/>
     * This method sets the value of the database column tb_trade_detail.price
     *
     * @param price the value for tb_trade_detail.price
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * 订单标题 <p/>
     * This method returns the value of the database column tb_trade_detail.goods_category
     *
     * @return the value of tb_trade_detail.goods_category
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getGoodsCategory() {
        return goodsCategory;
    }

    /**
     * 订单标题 <p/>
     * This method sets the value of the database column tb_trade_detail.goods_category
     *
     * @param goodsCategory the value for tb_trade_detail.goods_category
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setGoodsCategory(String goodsCategory) {
        this.goodsCategory = goodsCategory == null ? null : goodsCategory.trim();
    }

    /**
     * 对交易或商品的描述 <p/>
     * This method returns the value of the database column tb_trade_detail.body
     *
     * @return the value of tb_trade_detail.body
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getBody() {
        return body;
    }

    /**
     * 对交易或商品的描述 <p/>
     * This method sets the value of the database column tb_trade_detail.body
     *
     * @param body the value for tb_trade_detail.body
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * 买家的支付宝唯一用户号（2088开头的16位纯数字）,和buyer_logon_id不能同时为空 <p/>
     * This method returns the value of the database column tb_trade_detail.show_url
     *
     * @return the value of tb_trade_detail.show_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public String getShowUrl() {
        return showUrl;
    }

    /**
     * 买家的支付宝唯一用户号（2088开头的16位纯数字）,和buyer_logon_id不能同时为空 <p/>
     * This method sets the value of the database column tb_trade_detail.show_url
     *
     * @param showUrl the value for tb_trade_detail.show_url
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setShowUrl(String showUrl) {
        this.showUrl = showUrl == null ? null : showUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_detail.created
     *
     * @return the value of tb_trade_detail.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_detail.created
     *
     * @param created the value for tb_trade_detail.created
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_detail.modified
     *
     * @return the value of tb_trade_detail.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_detail.modified
     *
     * @param modified the value for tb_trade_detail.modified
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_trade_detail.enable_status
     *
     * @return the value of tb_trade_detail.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_trade_detail.enable_status
     *
     * @param enableStatus the value for tb_trade_detail.enable_status
     *
     * @mbggenerated Tue Aug 16 23:58:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}