package com.gcloud.shop.domain;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable {

    private static final long serialVersionUID = 7648969447092802536L;

    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_shop_user.id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private Long id;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_shop_user.store_id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String storeId;

    /**
     * 用户ID  <p/>
     * This field corresponds to the database column tb_shop_user.user_id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String userId;

    /**
     * 支付宝账户  <p/>
     * This field corresponds to the database column tb_shop_user.alipay_user_id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String alipayUserId;

    /**
     * 用户头像 <p/>
     * This field corresponds to the database column tb_shop_user.avatar
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String avatar;

    /**
     * 用户的真实姓名 <p/>
     * This field corresponds to the database column tb_shop_user.real_name
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String realName;

    /**
     * 用户邮箱地址 <p/>
     * This field corresponds to the database column tb_shop_user.email
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String email;

    /**
     * 用户证件号码 <p/>
     * This field corresponds to the database column tb_shop_user.cert_no
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String certNo;

    /**
     * 性别（F：女性；M：男性） <p/>
     * This field corresponds to the database column tb_shop_user.gender
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String gender;

    /**
     * 电话号码 <p/>
     * This field corresponds to the database column tb_shop_user.phone
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String phone;

    /**
     * 手机号码 <p/>
     * This field corresponds to the database column tb_shop_user.mobile
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String mobile;

    /**
     * 配置信息 <p/>
     * This field corresponds to the database column tb_shop_user.conf
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String conf;

    /**
     * 最后登录时间 <p/>
     * This field corresponds to the database column tb_shop_user.last_login_date
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String lastLoginDate;

    /**
     * 最后登录IP <p/>
     * This field corresponds to the database column tb_shop_user.last_login_ip
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_user.deadline
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_user.created
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_user.modified
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_shop_user.enable_status
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_shop_user.id
     *
     * @return the value of tb_shop_user.id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_shop_user.id
     *
     * @param id the value for tb_shop_user.id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_shop_user.store_id
     *
     * @return the value of tb_shop_user.store_id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_shop_user.store_id
     *
     * @param storeId the value for tb_shop_user.store_id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }

    /**
     * 用户ID  <p/>
     * This method returns the value of the database column tb_shop_user.user_id
     *
     * @return the value of tb_shop_user.user_id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * 用户ID  <p/>
     * This method sets the value of the database column tb_shop_user.user_id
     *
     * @param userId the value for tb_shop_user.user_id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * 支付宝账户  <p/>
     * This method returns the value of the database column tb_shop_user.alipay_user_id
     *
     * @return the value of tb_shop_user.alipay_user_id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getAlipayUserId() {
        return alipayUserId;
    }

    /**
     * 支付宝账户  <p/>
     * This method sets the value of the database column tb_shop_user.alipay_user_id
     *
     * @param alipayUserId the value for tb_shop_user.alipay_user_id
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setAlipayUserId(String alipayUserId) {
        this.alipayUserId = alipayUserId == null ? null : alipayUserId.trim();
    }

    /**
     * 用户头像 <p/>
     * This method returns the value of the database column tb_shop_user.avatar
     *
     * @return the value of tb_shop_user.avatar
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * 用户头像 <p/>
     * This method sets the value of the database column tb_shop_user.avatar
     *
     * @param avatar the value for tb_shop_user.avatar
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * 用户的真实姓名 <p/>
     * This method returns the value of the database column tb_shop_user.real_name
     *
     * @return the value of tb_shop_user.real_name
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * 用户的真实姓名 <p/>
     * This method sets the value of the database column tb_shop_user.real_name
     *
     * @param realName the value for tb_shop_user.real_name
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * 用户邮箱地址 <p/>
     * This method returns the value of the database column tb_shop_user.email
     *
     * @return the value of tb_shop_user.email
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * 用户邮箱地址 <p/>
     * This method sets the value of the database column tb_shop_user.email
     *
     * @param email the value for tb_shop_user.email
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 用户证件号码 <p/>
     * This method returns the value of the database column tb_shop_user.cert_no
     *
     * @return the value of tb_shop_user.cert_no
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * 用户证件号码 <p/>
     * This method sets the value of the database column tb_shop_user.cert_no
     *
     * @param certNo the value for tb_shop_user.cert_no
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * 性别（F：女性；M：男性） <p/>
     * This method returns the value of the database column tb_shop_user.gender
     *
     * @return the value of tb_shop_user.gender
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * 性别（F：女性；M：男性） <p/>
     * This method sets the value of the database column tb_shop_user.gender
     *
     * @param gender the value for tb_shop_user.gender
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * 电话号码 <p/>
     * This method returns the value of the database column tb_shop_user.phone
     *
     * @return the value of tb_shop_user.phone
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 电话号码 <p/>
     * This method sets the value of the database column tb_shop_user.phone
     *
     * @param phone the value for tb_shop_user.phone
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 手机号码 <p/>
     * This method returns the value of the database column tb_shop_user.mobile
     *
     * @return the value of tb_shop_user.mobile
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * 手机号码 <p/>
     * This method sets the value of the database column tb_shop_user.mobile
     *
     * @param mobile the value for tb_shop_user.mobile
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * 配置信息 <p/>
     * This method returns the value of the database column tb_shop_user.conf
     *
     * @return the value of tb_shop_user.conf
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getConf() {
        return conf;
    }

    /**
     * 配置信息 <p/>
     * This method sets the value of the database column tb_shop_user.conf
     *
     * @param conf the value for tb_shop_user.conf
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setConf(String conf) {
        this.conf = conf == null ? null : conf.trim();
    }

    /**
     * 最后登录时间 <p/>
     * This method returns the value of the database column tb_shop_user.last_login_date
     *
     * @return the value of tb_shop_user.last_login_date
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * 最后登录时间 <p/>
     * This method sets the value of the database column tb_shop_user.last_login_date
     *
     * @param lastLoginDate the value for tb_shop_user.last_login_date
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setLastLoginDate(String lastLoginDate) {
        this.lastLoginDate = lastLoginDate == null ? null : lastLoginDate.trim();
    }

    /**
     * 最后登录IP <p/>
     * This method returns the value of the database column tb_shop_user.last_login_ip
     *
     * @return the value of tb_shop_user.last_login_ip
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * 最后登录IP <p/>
     * This method sets the value of the database column tb_shop_user.last_login_ip
     *
     * @param lastLoginIp the value for tb_shop_user.last_login_ip
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_user.deadline
     *
     * @return the value of tb_shop_user.deadline
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_user.deadline
     *
     * @param deadline the value for tb_shop_user.deadline
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_user.created
     *
     * @return the value of tb_shop_user.created
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_user.created
     *
     * @param created the value for tb_shop_user.created
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_user.modified
     *
     * @return the value of tb_shop_user.modified
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_user.modified
     *
     * @param modified the value for tb_shop_user.modified
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_shop_user.enable_status
     *
     * @return the value of tb_shop_user.enable_status
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_shop_user.enable_status
     *
     * @param enableStatus the value for tb_shop_user.enable_status
     *
     * @mbggenerated Wed Aug 17 15:15:43 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}