package com.gcloud.shop.web.request;

import java.util.Date;

/**
* 【请求】订单支付请求参数<br/>
* mainCode = 1<br/>
* subCode = 1<br/>
* <p/>
* Created by game tools.
*/
public class AreaInfoReq extends BaseRequest {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.num_iid
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long numIid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.taobao_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long taobaoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.on_sale
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Boolean onSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.short_title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String shortTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.market
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String market;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.factory
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String factory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.goods_allocation
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String goodsAllocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.actual_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long actualStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.available_in_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long availableInStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.lock_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long lockStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.defective_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long defectiveStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.alarm_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long alarmStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.cost_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Double costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.weight
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.barcode
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.created
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.modified
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.enable_status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.pic_path
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String picPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.outer_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String outerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.num
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.alarm
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Integer alarm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.remark
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.type
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.cat_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.brand
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.seller_cids
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String sellerCids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.platform
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.props_name
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String propsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.unit
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.purchase_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Double purchasePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.selling_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Double sellingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.x
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Double x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.y
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Double y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.z
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Double z;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.period_cast
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Integer periodCast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.place
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.age
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.sys_item_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long sysItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.defined_1
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String defined1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.defined_2
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String defined2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.defined_3
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String defined3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.merge_type
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Boolean mergeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.num_iid
     *
     * @return the value of tb_goods_spu.num_iid
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getNumIid() {
        return numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.num_iid
     *
     * @param numIid the value for tb_goods_spu.num_iid
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setNumIid(Long numIid) {
        this.numIid = numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.id
     *
     * @return the value of tb_goods_spu.id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.id
     *
     * @param id the value for tb_goods_spu.id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.taobao_id
     *
     * @return the value of tb_goods_spu.taobao_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getTaobaoId() {
        return taobaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.taobao_id
     *
     * @param taobaoId the value for tb_goods_spu.taobao_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setTaobaoId(Long taobaoId) {
        this.taobaoId = taobaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.on_sale
     *
     * @return the value of tb_goods_spu.on_sale
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Boolean getOnSale() {
        return onSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.on_sale
     *
     * @param onSale the value for tb_goods_spu.on_sale
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setOnSale(Boolean onSale) {
        this.onSale = onSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.short_title
     *
     * @return the value of tb_goods_spu.short_title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getShortTitle() {
        return shortTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.short_title
     *
     * @param shortTitle the value for tb_goods_spu.short_title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setShortTitle(String shortTitle) {
        this.shortTitle = shortTitle == null ? null : shortTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.market
     *
     * @return the value of tb_goods_spu.market
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.market
     *
     * @param market the value for tb_goods_spu.market
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.factory
     *
     * @return the value of tb_goods_spu.factory
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getFactory() {
        return factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.factory
     *
     * @param factory the value for tb_goods_spu.factory
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setFactory(String factory) {
        this.factory = factory == null ? null : factory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.goods_allocation
     *
     * @return the value of tb_goods_spu.goods_allocation
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getGoodsAllocation() {
        return goodsAllocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.goods_allocation
     *
     * @param goodsAllocation the value for tb_goods_spu.goods_allocation
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setGoodsAllocation(String goodsAllocation) {
        this.goodsAllocation = goodsAllocation == null ? null : goodsAllocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.actual_stock
     *
     * @return the value of tb_goods_spu.actual_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getActualStock() {
        return actualStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.actual_stock
     *
     * @param actualStock the value for tb_goods_spu.actual_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setActualStock(Long actualStock) {
        this.actualStock = actualStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.available_in_stock
     *
     * @return the value of tb_goods_spu.available_in_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getAvailableInStock() {
        return availableInStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.available_in_stock
     *
     * @param availableInStock the value for tb_goods_spu.available_in_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setAvailableInStock(Long availableInStock) {
        this.availableInStock = availableInStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.lock_stock
     *
     * @return the value of tb_goods_spu.lock_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getLockStock() {
        return lockStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.lock_stock
     *
     * @param lockStock the value for tb_goods_spu.lock_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setLockStock(Long lockStock) {
        this.lockStock = lockStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.defective_stock
     *
     * @return the value of tb_goods_spu.defective_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getDefectiveStock() {
        return defectiveStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.defective_stock
     *
     * @param defectiveStock the value for tb_goods_spu.defective_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setDefectiveStock(Long defectiveStock) {
        this.defectiveStock = defectiveStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.alarm_stock
     *
     * @return the value of tb_goods_spu.alarm_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getAlarmStock() {
        return alarmStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.alarm_stock
     *
     * @param alarmStock the value for tb_goods_spu.alarm_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setAlarmStock(Long alarmStock) {
        this.alarmStock = alarmStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.cost_price
     *
     * @return the value of tb_goods_spu.cost_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Double getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.cost_price
     *
     * @param costPrice the value for tb_goods_spu.cost_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setCostPrice(Double costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.weight
     *
     * @return the value of tb_goods_spu.weight
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.weight
     *
     * @param weight the value for tb_goods_spu.weight
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.barcode
     *
     * @return the value of tb_goods_spu.barcode
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.barcode
     *
     * @param barcode the value for tb_goods_spu.barcode
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.created
     *
     * @return the value of tb_goods_spu.created
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.created
     *
     * @param created the value for tb_goods_spu.created
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.modified
     *
     * @return the value of tb_goods_spu.modified
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.modified
     *
     * @param modified the value for tb_goods_spu.modified
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.enable_status
     *
     * @return the value of tb_goods_spu.enable_status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.enable_status
     *
     * @param enableStatus the value for tb_goods_spu.enable_status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.pic_path
     *
     * @return the value of tb_goods_spu.pic_path
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.pic_path
     *
     * @param picPath the value for tb_goods_spu.pic_path
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.title
     *
     * @return the value of tb_goods_spu.title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.title
     *
     * @param title the value for tb_goods_spu.title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.outer_id
     *
     * @return the value of tb_goods_spu.outer_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.outer_id
     *
     * @param outerId the value for tb_goods_spu.outer_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setOuterId(String outerId) {
        this.outerId = outerId == null ? null : outerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.num
     *
     * @return the value of tb_goods_spu.num
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.num
     *
     * @param num the value for tb_goods_spu.num
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setNum(Long num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.alarm
     *
     * @return the value of tb_goods_spu.alarm
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Integer getAlarm() {
        return alarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.alarm
     *
     * @param alarm the value for tb_goods_spu.alarm
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setAlarm(Integer alarm) {
        this.alarm = alarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.remark
     *
     * @return the value of tb_goods_spu.remark
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.remark
     *
     * @param remark the value for tb_goods_spu.remark
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.type
     *
     * @return the value of tb_goods_spu.type
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.type
     *
     * @param type the value for tb_goods_spu.type
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.cat_id
     *
     * @return the value of tb_goods_spu.cat_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.cat_id
     *
     * @param catId the value for tb_goods_spu.cat_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setCatId(String catId) {
        this.catId = catId == null ? null : catId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.brand
     *
     * @return the value of tb_goods_spu.brand
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.brand
     *
     * @param brand the value for tb_goods_spu.brand
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.seller_cids
     *
     * @return the value of tb_goods_spu.seller_cids
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getSellerCids() {
        return sellerCids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.seller_cids
     *
     * @param sellerCids the value for tb_goods_spu.seller_cids
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setSellerCids(String sellerCids) {
        this.sellerCids = sellerCids == null ? null : sellerCids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.platform
     *
     * @return the value of tb_goods_spu.platform
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.platform
     *
     * @param platform the value for tb_goods_spu.platform
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.props_name
     *
     * @return the value of tb_goods_spu.props_name
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getPropsName() {
        return propsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.props_name
     *
     * @param propsName the value for tb_goods_spu.props_name
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setPropsName(String propsName) {
        this.propsName = propsName == null ? null : propsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.unit
     *
     * @return the value of tb_goods_spu.unit
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.unit
     *
     * @param unit the value for tb_goods_spu.unit
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.purchase_price
     *
     * @return the value of tb_goods_spu.purchase_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Double getPurchasePrice() {
        return purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.purchase_price
     *
     * @param purchasePrice the value for tb_goods_spu.purchase_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setPurchasePrice(Double purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.selling_price
     *
     * @return the value of tb_goods_spu.selling_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Double getSellingPrice() {
        return sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.selling_price
     *
     * @param sellingPrice the value for tb_goods_spu.selling_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setSellingPrice(Double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.x
     *
     * @return the value of tb_goods_spu.x
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Double getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.x
     *
     * @param x the value for tb_goods_spu.x
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setX(Double x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.y
     *
     * @return the value of tb_goods_spu.y
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Double getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.y
     *
     * @param y the value for tb_goods_spu.y
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setY(Double y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.z
     *
     * @return the value of tb_goods_spu.z
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Double getZ() {
        return z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.z
     *
     * @param z the value for tb_goods_spu.z
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setZ(Double z) {
        this.z = z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.period_cast
     *
     * @return the value of tb_goods_spu.period_cast
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Integer getPeriodCast() {
        return periodCast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.period_cast
     *
     * @param periodCast the value for tb_goods_spu.period_cast
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setPeriodCast(Integer periodCast) {
        this.periodCast = periodCast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.place
     *
     * @return the value of tb_goods_spu.place
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.place
     *
     * @param place the value for tb_goods_spu.place
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.age
     *
     * @return the value of tb_goods_spu.age
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.age
     *
     * @param age the value for tb_goods_spu.age
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.sys_item_id
     *
     * @return the value of tb_goods_spu.sys_item_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getSysItemId() {
        return sysItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.sys_item_id
     *
     * @param sysItemId the value for tb_goods_spu.sys_item_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setSysItemId(Long sysItemId) {
        this.sysItemId = sysItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.defined_1
     *
     * @return the value of tb_goods_spu.defined_1
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getDefined1() {
        return defined1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.defined_1
     *
     * @param defined1 the value for tb_goods_spu.defined_1
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setDefined1(String defined1) {
        this.defined1 = defined1 == null ? null : defined1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.defined_2
     *
     * @return the value of tb_goods_spu.defined_2
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getDefined2() {
        return defined2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.defined_2
     *
     * @param defined2 the value for tb_goods_spu.defined_2
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setDefined2(String defined2) {
        this.defined2 = defined2 == null ? null : defined2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.defined_3
     *
     * @return the value of tb_goods_spu.defined_3
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getDefined3() {
        return defined3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.defined_3
     *
     * @param defined3 the value for tb_goods_spu.defined_3
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setDefined3(String defined3) {
        this.defined3 = defined3 == null ? null : defined3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.merge_type
     *
     * @return the value of tb_goods_spu.merge_type
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Boolean getMergeType() {
        return mergeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.merge_type
     *
     * @param mergeType the value for tb_goods_spu.merge_type
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setMergeType(Boolean mergeType) {
        this.mergeType = mergeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.status
     *
     * @return the value of tb_goods_spu.status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.status
     *
     * @param status the value for tb_goods_spu.status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

}